### ISSUE TITLE
Error on preamble import

### ISSUE THREAD

**Issue by saptak** [amueller/introduction_to_ml_with_python#1]
I am getting the following error:

from preamble import *
%matplotlib inline
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8d9516cbe0a2> in <module>()
----> 1 from preamble import *
      2 get_ipython().magic(u'matplotlib inline')

/Users/ssen/Box Sync/projects/introduction_to_ml_with_python/preamble.py in <module>()
      2 import numpy as np
      3 import matplotlib.pyplot as plt
----> 4 import mglearn
      5 
      6 set_matplotlib_formats('pdf', 'png')

/Users/ssen/Box Sync/projects/introduction_to_ml_with_python/mglearn/__init__.pyc in <module>()
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 
      5 __all__ = ['tools', 'plots', 'cm3', 'cm2']

/Users/ssen/Box Sync/projects/introduction_to_ml_with_python/mglearn/plots.py in <module>()
      9                              plot_single_hidden_layer_graph,
     10                              plot_two_hidden_layer_graph)
---> 11 from .plot_linear_regression import plot_linear_regression_wave
     12 from .plot_tree_nonmonotonous import plot_tree_not_monotone
     13 from .plot_scaling import plot_scaling

/Users/ssen/Box Sync/projects/introduction_to_ml_with_python/mglearn/plot_linear_regression.py in <module>()
      3 
      4 from sklearn.linear_model import LinearRegression
----> 5 from sklearn.model_selection import train_test_split
      6 from .datasets import make_wave
      7 

ImportError: No module named model_selection

**Comment by amueller** [comment]
As the readme says, you need the development version of scikit-learn.
It will be released before the book is published.

**Comment by saptak** [comment]
Thank you amueller for the quick reply. I upgraded to the development version. I double checked as below but get the same error:
pip show scikit-learn
---
Metadata-Version: 1.1
Name: scikit-learn
Version: 0.18.dev0
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: Andreas Mueller
Author-email: amueller@ais.uni-bonn.de
License: new BSD
Location: /Users/ssen/anaconda/envs/dato-env/lib/python2.7/site-packages

**Comment by amueller** [comment]
if you run ``import sklearn; print(sklearn.__version__)``, what do you get?

**Comment by saptak** [comment]
Somehow, I am still getting

import sklearn; print(sklearn.__version__)

0.17.1

**Comment by amueller** [comment]
your pip and the python you are using belong to different python environments.

**Comment by saptak** [comment]
Looks like they are using the same python environment:

(dato-env)HW12341:introduction_to_ml_with_python ssen$ which pip

/Users/ssen/anaconda/envs/dato-env/bin/pip

(dato-env)HW12341:introduction_to_ml_with_python ssen$ which python

/Users/ssen/anaconda/envs/dato-env/bin/python

(dato-env)HW12341:introduction_to_ml_with_python ssen$ which ipython

/Users/ssen/anaconda/envs/dato-env/bin/ipython

**Comment by amueller** [comment]
If you install with conda, you shouldn't upgrade with pip. If you did that,
remove the scikit-learn folder and reinstall will pip.

**Comment by saptak** [comment]
Thanks that solved it

**Comment by ncdingari** [comment]
@amueller I am getting the "ImportError: No module named 'preamble'" even after upgrading scikit-learn to 

> import sklearn
> print(sklearn.__version__)
0.18.1

**Comment by Amirosimani** [comment]
Im also getting the error on: from preamble import *

I removed scikit-learn and re-installed with pip. running import sklearn; print(sklearn.__version__) , I get: 0.18.1
any suggestions how to fix it?

**Comment by amueller** [comment]
What's the error?
Please provide the full traceback.

**Comment by Amirosimani** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-2-5b4fe434f1a9> in <module>()
      1 import mglearn
      2 get_ipython().magic('matplotlib inline')
----> 3 from preamble import *
      4 
      5 X, y = mglearn.datasets.make_forge()

ImportError: No module named 'preamble'

**Comment by amueller** [comment]
How are you running the notebooks? This repository contains the notebooks, and along with the notebooks a file called ``preamble.py`` that is imported here. Make sure that this file is present when running the notebook.

**Comment by aduk4u** [comment]
Hello guys, I need help. I get error when i try to execute this command;
mglearn.plots.plot_two_hidden_layer_graph()

I always have the following error tracebacks


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-33-4754c4bed350> in <module>()
      1 import mglearn
----> 2 mglearn.plots.plot_two_hidden_layer_graph()

C:\Users\SK\.ipython\mglearn\plot_nn_graphs.py in plot_two_hidden_layer_graph()
     65 
     66 def plot_two_hidden_layer_graph():
---> 67     import graphviz
     68     nn_graph = graphviz.Digraph(node_attr={'shape': 'circle', 'fixedsize': 'True'},
     69                                 graph_attr={'rankdir': 'LR', 'splines': 'line'})

ModuleNotFoundError: No module named 'graphviz

How can i fix it. I am running Notebook on windows

**Comment by amueller** [comment]
@aduk4u this sounds like an unrelated issue, right? If you're using conda, you can ``conda install graphviz-python graphviz`` as described in the readme: https://github.com/amueller/introduction_to_ml_with_python#installing-packages-with-conda

If you're not using conda, you can install the required python library with ``pip install graphviz`` but installing the supporting executable is more tricky. This function will only reproduce the figure you can see in the book, by the way, so it's not that important.

**Comment by aduk4u** [comment]
Hello Andrea, I'm very glad to get your response. it really helped me a
lot. I need an idea on how to change the weight and activation function to
memristive model function that can perform faster and same as the logistic
or Relu function. I'm working to classify breast cancer. I would like you
to help me.

Thanks and waiting for your response.

My regards
Adu

**Comment by amueller** [comment]
@aduk4u Sorry I can't help you with that.
