### ISSUE TITLE
Jupyter Notebook Cannot Find Pandas

### ISSUE THREAD

**Issue by wpr101** [amueller/introduction_to_ml_with_python#10]
Hey, I am having some difficulty getting the examples to run in the Jupyter Notebook.

When I have it set to be a Python3 script it cannot find pandas or many other libraries.

Yet, when do a '!pip list' command it shows up fine. Any ideas?

Also I cannot get the 'display(data_pandas)' on page 10 to work. It says display is an unrecognized command.

**Comment by TerrySnow1963** [comment]
I am having the same trouble for 'display(data_pandas)' on page 10, I get a name error for "display".
I have used anaconda to install the python distribution, and am running on OS X 10.11.6

**Comment by TerrySnow1963** [comment]
Found solution to name error on display, needed to add line

from IPython.display import display

found the solution by reading jupyter documentation at

https://nbviewer.jupyter.org/github/ipython/ipython/blob/3.x/examples/IPython%20Kernel/Rich%20Output.ipynb

**Comment by amueller** [comment]
@TerrySnow1963 you might not have run the first cell in the notebook, which imports ``preamble``. The preamble contains this import.

**Comment by wpr101** [comment]
I don't see that line in the book though? The book just starts with line 2 on page 7. 

Also, what is preamble? I tried doing a pip install preamble but it is not recognized.

**Comment by amueller** [comment]
That line is not in the book. The bottom of page 11 mentions most of what's happening in the preamble, but I forgot the ``from IPython.display import display`` line.
If you use the notebook and packages from the repository, they contain the preamble.py that does all the necessary imports.

**Comment by amueller** [comment]
The first line in all jupyter notebooks in this repository is ``from preamble import *``

**Comment by amueller** [comment]
I added a comment about this to the README and fixed it in the book (so it will be fixed in future prints / releases of the ebook).
