### ISSUE TITLE
CountVectorizer not working

### ISSUE THREAD

**Issue by yhzheng89** [amueller/introduction_to_ml_with_python#104]
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_process).fit(X)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-19528c66ddaa> in <module>
      1 from sklearn.feature_extraction.text import CountVectorizer
----> 2 bow_transformer = CountVectorizer(analyzer=text_process).fit(X)

NameError: name 'text_process' is not defined

**Comment by amueller** [comment]
Can you give a bit more context? This snippet doesn't seem to be from the book or the notebooks.
And clearly ``text_process`` is not defined, as the error says.

**Comment by Anuragsangem** [comment]
even I was facing the same issue did you find a solution/alternative for this?

**Comment by amueller** [comment]
@Anuragsangem again, can you give more context? What was the code and what was the error?

**Comment by harshgeek4coder** [comment]
Even i am having the same issue

**Comment by amueller** [comment]
@harshgeek4coder can you please describe the issue? What is the code, where in the book is it from, and what is the error?

**Comment by harshgeek4coder** [comment]
@amueller  Nope.. it worked .. i tried some new code while fixing it with changing the ratio of test split..Thanks Anyways.
