### ISSUE TITLE
How to install mglearn using anaconda

### ISSUE THREAD

**Issue by TerrySnow1963** [amueller/introduction_to_ml_with_python#11]
Sorry for beginners question, I had already spent a few days searching for instructions...

I have bought your book, and am trying to follow the examples and setup. 
I have installed anaconda on OS X. 
I have used github to download mglearn.

Now, I am looking for how to install mglearn in anaconda.

Many thanks

**Comment by amueller** [comment]
You don't need to install mglearn. If you run the jupyter notebooks that you downloaded from this repository, it will automatically find the mglearn library.
If, for some reason, you want to use tools from mglearn outside of the notebooks, you can run ``pip install mglearn``

**Comment by TerrySnow1963** [comment]
Thanks for info, I will try it out

**Comment by TerrySnow1963** [comment]
Worked fine, thanks
