### ISSUE TITLE
Working with Movie Review data

### ISSUE THREAD

**Issue by TQuy** [amueller/introduction_to_ml_with_python#111]
when I loaded the files in the train Folder, and printed out the length of text_train following In[3] in page 326, I got "length of text_train: 75000", which is much larger compared to 25000 in the book (first edition). In addition, after running code in the cell In[6] page, I got "Samples per class (training): [12500 12500 50000]". I want to ask what category the remaining 50000 reviews belong to? and how to reduce the number of samples down to 25000 because it takes quite long to run each cell

**Comment by TQuy** [comment]
i downloaded the rar file from the link http://ai.stanford.edu/~amaas/data/sentiment/

**Comment by amueller** [comment]
Sorry for the slow reply, you have to remove the ``unsup`` folder from the training data, which should be explained in the book.

**Comment by TQuy** [comment]
Thank you for your reply.
I have known that I need to delete the unsup folder, so I closed my
question because I don't know how to delete it.
In addition, I am having trouble running the chapter 7 since the data is
quite large for my laptop. Consequently, I am wondering if I can use Google
colab to run chapter 7? My friend suggested my to do so

On Jan 16, 2019 3:00 AM, "Andreas Mueller" <notifications@github.com> wrote:

Sorry for the slow reply, you have to remove the unsup folder from the
training data, which should be explained in the book.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/amueller/introduction_to_ml_with_python/issues/111#issuecomment-454530211>,
or mute the thread
