### ISSUE TITLE
Utilizing Expert Knowledge

### ISSUE THREAD

**Issue by hokagedemehin** [amueller/introduction_to_ml_with_python#115]
Hi mueller,

The code used to define the variable x is not running. This is the code

X=citobike.index.strftime(%s).astype("int"). reshape (-1,1)

And also i am getting the error when i created the function "eval_on_features", xticks is not defined

Will wait for your response

Thanks

**Comment by amueller** [comment]
Hey. Sorry for the slow reply. What is the error message and which version of pandas are you using? This line had to change because of several changes of pandas over the last couple of years. Try the one provided in the notebooks in this repo, which is for the current version of pandas.

**Comment by amueller** [comment]
closing as no reply
