### ISSUE TITLE
pandas.scatter_matrix solved

### ISSUE THREAD

**Issue by DevSkyWalker** [amueller/introduction_to_ml_with_python#116]
Love the book very comprehensive! time seems to acquire inevitable changes in frameworks it seems. The book references code for the iris classification problem using **pandas.scatter_matrix**  in the book to get the plot working simply change it to **pandas.plotting.scatter_matrix**  this resolved the issue for me. Great book!

**Comment by amueller** [comment]
This is changed in the newer prints of the book. This was change in pandas after the first book was released and unfortunately print copies are hard to update ;)
