### ISSUE TITLE
Error in: mglearn.plot_shuffle_split()

### ISSUE THREAD

**Issue by konfer** [amueller/introduction_to_ml_with_python#117]
get the error info 👍 
"ss = ShuffleSplit(n_iter=4, train_size=5, test_size=2, random_state=43)
     69     mask = np.zeros((n_iter, n_samples))
     70     for i, (train, test) in enumerate(ss.split(range(10))):

TypeError: __init__() got an unexpected keyword argument 'n_iter'"

the api of ShuffleSplit in the nearest sklearn is changed from "n_iter" to "n_split"

**Comment by amueller** [comment]
Hey.
Thanks for the input. Which version of mglearn is that?
