### ISSUE TITLE
Error in: mglearn.plots.plot_group_kfold()

### ISSUE THREAD

**Issue by konfer** [amueller/introduction_to_ml_with_python#118]
get the error :

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-a2f3201c2ee5> in <module>()
----> 1 mglearn.plots.plot_group_kfold()

AttributeError: module 'mglearn.plots' has no attribute 'plot_group_kfold'
------------------------------------------------------------------------

**Comment by amueller** [comment]
Thanks for the report. Which version of mglearn is that and how did you install it? Which version of scikit-learn are you using?

**Comment by melaniekrause** [comment]
Hello! I get the same error measure as the user above when trying to run mglearn.plots.plot_label_kfold()
My version of mglearn is 0.1.7. I use Spyder and import mglearn via "import mglearn".
Any ideas what I can do to produce "Figure 5-4. Label-dependent splitting with GroupKFold"?
Thanks in advance!

**Comment by amueller** [comment]
Hi. Have you checked that the version of mglearn you're importing is actually 0.1.7? It might be that you have different versions of mglearn in different environments, and Spyder uses an older version.

**Comment by melaniekrause** [comment]
Hi, thanks for the response. Actually, I found the error: I was using the command mglearn.plots.plot_label_kfold() as printed in your book, while you had changed and replaced "label" with "group" after the publication... Happy to found resolved this issue!
By the way, your book is really great and I use parts of the code and examples when teaching an ML course.

**Comment by amueller** [comment]
Oh, right. Sorry I should have seen this. You seem to have a very early print of the book. Btw, the slides for my course are also available online if you're interested:
https://www.cs.columbia.edu/~amueller/comsw4995s20/schedule/

(and the videos: https://youtube.com/andreasmueller )
