### ISSUE TITLE
Errata: Potential typo in text on page 59

### ISSUE THREAD

**Issue by NathanielWroblewski** [amueller/introduction_to_ml_with_python#12]
I didn't find the text online or I would've opened a PR, and I'm unsure if you are even interested in collecting errata, but I believe there is a typo on pg 59 (Chapter 2: Supervised Learning):

> Let's analyze `LinearLogistic` in more detail on the Breast Cancer dataset:

The section is discussing linear SVM and logisitic regression, and I think they were just combined accidentally.  I believe the text should be corrected to:

> Let's analyze `LogisticRegression` in more detail on the Breast Cancer dataset:

**Comment by amueller** [comment]
Hi @NathanielWroblewski.
Thanks for the errata. You can submit them here: http://www.oreilly.com/catalog/errata.csp?isbn=0636920030515 which makes sure they'll be fixed in the book and ebook.

**Comment by amueller** [comment]
Actually, I just fixed this in the book, so don't worry about this one, but please submit future errata through that system. Thanks again!
