### ISSUE TITLE
ZZ = (coef[0] * XX + coef[1] * YY + intercept) / -coef[2]  

### ISSUE THREAD

**Issue by ranabanik** [amueller/introduction_to_ml_with_python#120]
`coef` is a vector of (12,) and both `XX` and `YY` are arrays of (50,50). `intercept` is a vector of (4,). So the broadcasting does not work between (50,50) array and (4,) vector. 
The problem is in 97th page of the book and in supervised learning `LinearSVM` section.

**Comment by amueller** [comment]
Sorry can you please give more context?
What is the line that causes the error and what is the error message?
It's likely that you ran code in a different order than it is in the book.

**Comment by SukhboldAltangerel** [comment]
Hello sir, I am getting the same error in 79th line of '02-supervised-learning' IPython notebook.
The equation ZZ = (coef[0] * XX + coef[1] * YY + intercept) / -coef[2] raises 'ValueError: operands could not be broadcast together with shapes (50,50) (4,)'. How do we elevate 50x50 grid in 3d plotting with (4,) shaped intercept.

**Comment by amueller** [comment]
the shape of the intercept should be ``(1,)``, ``coef`` has shape ``(3,)``. What data are you fitting the model on?

**Comment by SukhboldAltangerel** [comment]
Fitting 'linear_svm_3d = LinearSVC().fit(X_new, y)' model where 'X_new' got shape of (100, 3) and 'y' got shape of (100,) and unique value of 4.
Oh I missed the 'y = y % 2' transformation in the 76th line above. I see where I went wrong, thanks for your help sincerely.

**Comment by amueller** [comment]
no worries.
