### ISSUE TITLE
ValueError: coeffients must be 1d array or column vector

### ISSUE THREAD

**Issue by hanyun2019** [amueller/introduction_to_ml_with_python#121]
In the chapter "Rescaling the data with TFIDF":

mglearn.tools.visualize_coefficients(
    grid.best_estimator_.named_steps["logisticregression"].coef_,
    feature_names, n_top_features=40)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-15344be6c179> in <module>
      1 mglearn.tools.visualize_coefficients(
      2     grid.best_estimator_.named_steps["logisticregression"].coef_,
----> 3     feature_names, n_top_features=40)

/Users/research/MLPython/mglearn/tools.py in visualize_coefficients(coefficients, feature_names, n_top_features)
     28         # this is not a row or column vector
     29         raise ValueError("coeffients must be 1d array or column vector, got"
---> 30                          " shape {}".format(coefficients.shape))
     31     coefficients = coefficients.ravel()
     32 

ValueError: coeffients must be 1d array or column vector, got shape (3, 44532)

Please help what problem here. Thanks~

**Comment by amueller** [comment]
The current function only works for binary classification, you have a three-class problem. How did you load the data? You need to provide ``categories=['pos', 'neg']`` to the ``load_files`` function.

**Comment by hanyun2019** [comment]
Thanks a bot~

Andreas Mueller <notifications@github.com> 于2019年10月20日周日 下午8:38写道：
