### ISSUE TITLE
ModuleNotFoundError scikit version 0.21.3

### ISSUE THREAD

**Issue by bisandud** [amueller/introduction_to_ml_with_python#122]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3a78e8b263d8> in <module>
      3 import matplotlib.pyplot as plt
      4 import pandas as pd
----> 5 import mglearn

ModuleNotFoundError: No module named 'mglearn'

**Comment by amueller** [comment]
Please see the instructions in the readme: https://github.com/amueller/introduction_to_ml_with_python
