### ISSUE TITLE
Getting below error "make_blob is deprecated"on importing forge dataset

### ISSUE THREAD

**Issue by sushilkrtr** [amueller/introduction_to_ml_with_python#123]
<img width="286" alt="Capture3" src="https://user-images.githubusercontent.com/54894067/68240752-75ecb280-0033-11ea-9e89-aba46967f9a9.PNG">
<img width="257" alt="Capture4" src="https://user-images.githubusercontent.com/54894067/68240761-784f0c80-0033-11ea-9b15-8cd54607b0df.PNG">
<img width="276" alt="Capture1" src="https://user-images.githubusercontent.com/54894067/68240532-21493780-0033-11ea-8df1-8c9b8b45a72b.PNG">
<img width="771" alt="Capture2" src="https://user-images.githubusercontent.com/54894067/68240558-2c03cc80-0033-11ea-8532-89233145ffba.PNG">

**Comment by amueller** [comment]
This is a warning, not an error, and can be savely ignored. How and when did you install mglearn? This should have been fixed in recent version.
can you provide ``mglearn.__version__``?
