### ISSUE TITLE
not found mglearn

### ISSUE THREAD

**Issue by javed103** [amueller/introduction_to_ml_with_python#126]
ImportError                               Traceback (most recent call last)
<ipython-input-42-8cdb4ee918d2> in <module>
      4 import scipy as sp
      5 import pandas as pd
----> 6 import mglearn
      7 
      8 

c:\users\jade kamyana\appdata\local\programs\python\python37\lib\site-packages\mglearn\__init__.py in <module>
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 from .tools import discrete_scatter
      5 from .plot_helpers import ReBl

c:\users\jade kamyana\appdata\local\programs\python\python37\lib\site-packages\mglearn\plots.py in <module>
----> 1 from .plot_linear_svc_regularization import plot_linear_svc_regularization
      2 from .plot_interactive_tree import plot_tree_progressive, plot_tree_partition
      3 from .plot_animal_tree import plot_animal_tree
      4 from .plot_rbf_svm_parameters import plot_svm
      5 from .plot_knn_regression import plot_knn_regression

c:\users\jade kamyana\appdata\local\programs\python\python37\lib\site-packages\mglearn\plot_linear_svc_regularization.py in <module>
      1 import matplotlib.pyplot as plt
      2 import numpy as np
----> 3 from sklearn.svm import LinearSVC
      4 from sklearn.datasets import make_blobs
      5 

c:\users\jade kamyana\appdata\local\programs\python\python37\lib\site-packages\sklearn\__init__.py in <module>
     73     from . import __check_build
     74     from .base import clone
---> 75     from .utils._show_versions import show_versions
     76 
     77     __check_build  # avoid flakes unused variable error

c:\users\jade kamyana\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\_show_versions.py in <module>
     10 import importlib
     11 
---> 12 from ._openmp_helpers import _openmp_parallelism_enabled
     13 
     14 

ImportError: DLL load failed: The specified module could not be found.

**Comment by amueller** [comment]
Thanks for raising the issue. This is actually an issue with scikit-learn 0.22.
There will be a new release of scikit-learn 0.22.1 today that will hopefully resolve the issue. You can also install an older version of scikit-learn by using ``pip install scikit-learn==0.21.2`` (or using conda if that's how you installed sklearn)
