### ISSUE TITLE
AttributeError: module 'mglearn' has no attribute 'plot_helpers'

### ISSUE THREAD

**Issue by JorgeOlmeda** [amueller/introduction_to_ml_with_python#127]
Hi, sorry for disturb you,
I have bought your book last Christmas and I have some experience with python and jupyter.
In the previous version of this issue I comment some problems.
I have solved the problems.
But now I have a warning about a deprecation 
from preamble import *
%matplotlib inline

/home/alfred/.local/lib/python3.7/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)

I think that this warning can be interesting to you.

Many thanks

**Comment by amueller** [comment]
Thanks, I'm aware of the warning. I need to update mglearn for scikit-learn 0.22. You can ignore the warning, though.
