### ISSUE TITLE
Error trying to import mglearn

### ISSUE THREAD

**Issue by kreegah** [amueller/introduction_to_ml_with_python#13]
In [14]:

import mglearn

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-e19748f92cd9> in <module>()
----> 1 import mglearn

C:\Anaconda3\lib\site-packages\mglearn\__init__.py in <module>()
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 from .tools import discrete_scatter
      5 from .plot_helpers import ReBl

C:\Anaconda3\lib\site-packages\mglearn\plots.py in <module>()
      9                              plot_single_hidden_layer_graph,
     10                              plot_two_hidden_layer_graph)
---> 11 from .plot_linear_regression import plot_linear_regression_wave
     12 from .plot_tree_nonmonotonous import plot_tree_not_monotone
     13 from .plot_scaling import plot_scaling

C:\Anaconda3\lib\site-packages\mglearn\plot_linear_regression.py in <module>()
      3 
      4 from sklearn.linear_model import LinearRegression
----> 5 from sklearn.model_selection import train_test_split
      6 from .datasets import make_wave
      7 from .plot_helpers import cm2

C:\Anaconda3\lib\site-packages\sklearn\model_selection\__init__.py in <module>()
     15 from ._split import check_cv
     16 
---> 17 from ._validation import cross_val_score
     18 from ._validation import cross_val_predict
     19 from ._validation import learning_curve

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in <module>()
     24 from ..utils.fixes import astype
     25 from ..utils.validation import _is_arraylike, _num_samples
---> 26 from ..utils.metaestimators import _safe_split
     27 from ..externals.joblib import Parallel, delayed, logger
     28 from ..metrics.scorer import check_scoring

ImportError: cannot import name '_safe_split'

What have I done wrong?

Update: it works now, after restarting Jupyter. Sorry, my bad.

**Comment by kreegah** [comment]
Uh by the way I checked the module ..utils.metaestimators.py and sure enough, _safe_split was there. 

What now?

**Comment by NathanielWroblewski** [comment]
@kreegah do you mean to close this issue with your recent update?
> Update: it works now, after restarting Jupyter. Sorry, my bad.

**Comment by kreegah** [comment]
Yes sorry

**Comment by amueller** [comment]
there was probably an issue with your scikit-learn installation, but as far as I understand, it's fixed now, right? Sorry I was out over thanksgiving.
