### ISSUE TITLE
can't install mglearn

### ISSUE THREAD

**Issue by redleafnew** [amueller/introduction_to_ml_with_python#131]

**Comment by redleafnew** [comment]
(base) C:\Users\Wens>conda install mglearn
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mglearn

Current channels:

  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/win-64
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/win-64
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by redleafnew** [comment]
when I copy the downloaded mglearn to sit-package directory and import mglearn,
it prompt me:
d:\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)

**Comment by amueller** [comment]
Please see the instructions, they say ``pip install mglearn``.
You can ignore the warning about six being deprecated for now.

**Comment by shivamshan** [comment]
pip install mglearn shows the following message:-
Traceback (most recent call last):
  File "C:\Users\Shivam Shandilya\anaconda3\Scripts\pip-script.py", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'

**Comment by amueller** [comment]
@shivamshan please check out https://github.com/pypa/pip/issues/5373

**Comment by shivamshan** [comment]
> @shivamshan please check out [pypa/pip#5373](https://github.com/pypa/pip/issues/5373)

thank you @amueller the issue is fixed...i just had to update my pip version
