### ISSUE TITLE
Problem with plt.boxplot(X_train, manage_xticks= False)

### ISSUE THREAD

**Issue by Hypertyz** [amueller/introduction_to_ml_with_python#133]
`TypeError`    
`Traceback (most recent call last)`

`<ipython-input-96-564aeedf8d76> in <module>`
`----> 1 plt.boxplot(X_train, manage_xticks= False)`
      `2 plt.yscale("symlog")`
      `3 plt.xlabel("Feature index")`
      `4 plt.ylabel("Feature magnitude")`

`TypeError: boxplot() got an unexpected keyword argument 'manage_xticks'`

**Comment by SuperKogito** [comment]
Please provide a description to your code! 
The error is clear; from https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.boxplot.html, you can see that `boxplot()` has no argument `manage_xticks` but rather `manage_ticks`.

**Comment by Hypertyz** [comment]
Thanks! That was the problem. I was just copying the code directly from the book tho and the author wrote `manage_xticks` instead of `manage_ticks`

**Comment by amueller** [comment]
That must have been a change in the matplotlib API at some point. I'll keep it open as it needs to be fixed in the book.
