### ISSUE TITLE
While importing mglearn message appears "cannot import name 'imread' from 'scipy.misc'"

### ISSUE THREAD

**Issue by aeugene1977** [amueller/introduction_to_ml_with_python#134]
![image](https://user-images.githubusercontent.com/64860370/81096181-b1970500-8f0e-11ea-9bd2-9c607d2a208d.png)

**Comment by amueller** [comment]
Thanks for reporting the issue. Which version of mglearn do you have installed and how did you install it?

**Comment by aeugene1977** [comment]
> Thanks for reporting the issue. Which version of mglearn do you have installed and how did you install it?
I downloaded mglearn from github, here is only one version, I don't see version number. Then I saved it in folder where anaconda packets are installed (numpy, scipy etc.) No other instructions I have found.

**Comment by amueller** [comment]
Well the instructions in the readme of this repo and in the book say to run ``pip install mglearn``: https://github.com/amueller/introduction_to_ml_with_python

If you do that, there'll be a ``mglearn.__version__`` that tells you which version you're using.

**Comment by aeugene1977** [comment]
Thanks, Andreas, it works.
