### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.six'

### ISSUE THREAD

**Issue by dhdistc** [amueller/introduction_to_ml_with_python#135]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-610999fb3dd0> in <module>
      2 import matplotlib.pyplot as plt
      3 import pandas as pd
----> 4 import mglearn

e:\tools\python\lib\site-packages\mglearn\__init__.py in <module>
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 from .tools import discrete_scatter
      5 from .plot_helpers import ReBl

e:\tools\python\lib\site-packages\mglearn\plots.py in <module>
      1 from .plot_linear_svc_regularization import plot_linear_svc_regularization
----> 2 from .plot_interactive_tree import plot_tree_progressive, plot_tree_partition
      3 from .plot_animal_tree import plot_animal_tree
      4 from .plot_rbf_svm_parameters import plot_svm
      5 from .plot_knn_regression import plot_knn_regression

e:\tools\python\lib\site-packages\mglearn\plot_interactive_tree.py in <module>
      4 from sklearn.tree import DecisionTreeClassifier
      5 
----> 6 from sklearn.externals.six import StringIO  # doctest: +SKIP
      7 from sklearn.tree import export_graphviz
      8 from imageio import imread

ModuleNotFoundError: No module named 'sklearn.externals.six'

**Comment by amueller** [comment]
Thanks for reporting. You can change the import to ``from io import StringIO`` locally if you like, I'll push a fix shortly.

**Comment by amueller** [comment]
pushed a fix to this repo and mglearn, let me know if it works!
