### ISSUE TITLE
load_extendend_boston not found

### ISSUE THREAD

**Issue by m-hammaad** [amueller/introduction_to_ml_with_python#137]
When I run the following command on my system,

X, y = mglearn.datasets.load_extenden_boston()

I get the AttributeError

module 'mglearn.datasets' has no attribute 'load_extenden_boston'

**Comment by amueller** [comment]
Sorry for the slow reply, I hadn't seen this. There's a typo in your code, it should be ``load_extended_boston``, hope that helps.
