### ISSUE TITLE
Logistic Regression output with sklearn versions > 0.22

### ISSUE THREAD

**Issue by BerengereG** [amueller/introduction_to_ml_with_python#149]
I have been puzzled with the output of `LogisticRegression` from p59 to 61. The issue is that I have been using sklearn version 0.24 and [the default parameter for solver changed between version 0.20 and 0.22](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) from 'liblinear’ to ‘lbfgs’ + we now have to specify a `max_iter` parameter.

**Comment by amueller** [comment]
you don't have to specify it, but the default value gives you convergence warnings more often now (it's not entirely clear to me if increasing the number of iterations is the right fix, we actually just never showed convergence warnings from liblinear).
