### ISSUE TITLE
tkinter module can't be imported

### ISSUE THREAD

**Issue by lingvisa** [amueller/introduction_to_ml_with_python#15]
I am using Python 3.5.2 on CentOS 7.  I installed "yum install python3-tkinter" but it seems only working with Python 3.3, as shown by message below:

Package python3-tkinter-3.3.2-12.el7.nux.x86_64 already installed and latest version

How to make it working with Python 3.5?

**Comment by lingvisa** [comment]
As I imported mglearn, I received this message: "ImportError: No module named 'tkinter'"

**Comment by amueller** [comment]
Hey @lingvisa, sorry for the slow reply.
You could either install tkinter in your python3.5 environment using conda or pip (depending on whether you use a conda environment or a "normal" python environment).

> conda install tkinter

should do it.

Or, you could configure matplotlib to use a different backend:
http://matplotlib.org/faq/usage_faq.html#what-is-a-backend

**Comment by lingvisa** [comment]
@amueller canda works. Thank you.

**Comment by amueller** [comment]
Great :)
