### ISSUE TITLE
unable to open 02-supervised-learning.ipynb 

### ISSUE THREAD

**Issue by Richard-Bian** [amueller/introduction_to_ml_with_python#151]
Unreadable Notebook: C:\Users\user\Desktop\02-supervised-learning.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")

**Comment by amueller** [comment]
How did you download the notebook? Generally it's best to download the full repository as a ZIP file and unpack it.

**Comment by Richard-Bian** [comment]
thanks，I  made it。
