### ISSUE TITLE
AttributeError: module 'mglearn' has no attribute 'plot_helpers'

### ISSUE THREAD

**Issue by baqwas** [amueller/introduction_to_ml_with_python#154]
Hello!

After cloning the repository, I ran the first line in the notebook, _01-introduction.ipyng_, and encountered the following error message:
`AttributeError: module 'mglearn' has no attribute 'plot_helpers'`

Is this an operator/user self-inflicted error?

Thanks.

My platform information (derived from the code in the notebook a few lines later) is:
```
Python version: 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0]
pandas version: 1.2.4
matplotlib version: 3.4.1
NumPy version: 1.19.5
SciPy version: 1.6.3
IPython version: 7.23.1
scikit-learn version: 0.24.2
graphviz version: 0.17
```

**Comment by baqwas** [comment]
Operator error presumably. I ran _./mglearn/plot_helpers.py_ autonomously and then re-ran the original notebook, _01-introduction.ipyng._ Everything worked as documented. Sorry for the false alarm. 

Kind regards.

**Comment by amueller** [comment]
Glad it worked out in the end :)

**Comment by imkhali** [comment]
I am having the same exact error, I don't know what is wrong. I did not get how @baqwas solved the problem.

**Comment by wanghedy** [comment]
您的邮件已收到，我将会尽快处理，谢谢。王宇凝

**Comment by baqwas** [comment]
> @imkhali 

I ran **./mglearn/plot_helpers.py**.
I have visited this topic recently but will be willing to assist to help you further if you wish. Thanks.

Kind regards.

**Comment by BlackLutos** [comment]
I add  **from mglearn import plot_helpers**.
And I revised ~~cycler('color', mglearn.plot_helpers.cm_cycle.colors)~~  to   **cycler('color', plot_helpers.cm_cycle.colors)**.

Kind regards.

**Comment by zty-dalao** [comment]
> 我从 **mglearn import plot_helpers** 添加。我将 ~cycler（'color'， mglearn.plot_helpers.cm_cycle.colors）~ 修改为 **cycler（'color'， plot_helpers.cm_cycle.colors）。**
> 
> 亲切问候。

Thanks bro. It works
