### ISSUE TITLE
Value Error in cell24 in 05-model-evaluation-and-improvement.ipynb

### ISSUE THREAD

**Issue by HidemotoNakada** [amueller/introduction_to_ml_with_python#156]
I've got the following error with matplotlib 3.4.3.
```
ValueError: The number of FixedLocator locations (21), usually from a
call to set_ticks, does not match the number of ticklabels (36).
```

I believe this is due to a bug in mglearn/plot_grid_search.py, where the
labels are generated from the original 'cv_results_' instead of 'results'.
New version of matplotlib is stricter than the previous versions and 
revealed the existing bug in the code.

```
37:    plt.xticks(range(len(results)), [str(x).strip("{}").replace("'", "") for x
38:                                     in grid_search.cv_results_['params']],
39:                                      rotation=90)
```

line 38  should be 
```
                                            in results['params']], 
```

**Comment by wanghedy** [comment]
您的邮件已收到，我将会尽快处理，谢谢。王宇凝

**Comment by amueller** [comment]
Thank you! Fixed in a new release of mglearn.
