### ISSUE TITLE
Notation of Linear Regression Model

### ISSUE THREAD

**Issue by lingvisa** [amueller/introduction_to_ml_with_python#16]
![linear-regression](https://cloud.githubusercontent.com/assets/7905135/20816635/34f26078-b7d8-11e6-803e-f401956fd453.png)
![linear-regression2](https://cloud.githubusercontent.com/assets/7905135/20816637/37debfde-b7d8-11e6-9d07-86831d5f8a3b.png)

The first photo shows Andrew Ng's notation on linear notation, and the second one is from the book. What does 'b' correspond to Andrew's notation in the formula? My understanding is that the theta0x0 is equivalent to the b (b * 1, where '1' is x). If that case, is 'b' still necessary in the formula? Thank you.

**Comment by lingvisa** [comment]
Should the w[0] * x[0] be written as w[1]*x[1]?

**Comment by amueller** [comment]
b is ``\theta_0``. Both are common forms to write the equation. His is easy to write as a dot product, but he needs to introduce a dummy variable x[0] that is 1. And his features start with x[1], mine start with x[0].

**Comment by lingvisa** [comment]
If 'b' is theta_0, it seems duplicating with w[0]* x[0]? I understand w[0]* is the theta_0.

**Comment by amueller** [comment]
my x[0] is not 1. I'm not sure what you're asking.
If you have a feature array ``x`` of length ``n_features``, you can compute the decision function as
```python
y = np.dot(x, w) + b
```
For Andrew Ng's version, you have to do
```python
x_with_constant = np.hstack([[1], x])
y = np.dot(x_with_constant, theta)
```

**Comment by lingvisa** [comment]
Thank you. Amueller.

**Comment by amueller** [comment]
glad I could clarify.
