### ISSUE TITLE
Bug in plot_cross_val_selection method

### ISSUE THREAD

**Issue by karitonov** [amueller/introduction_to_ml_with_python#161]
[plot_grid_search.py](https://github.com/amueller/introduction_to_ml_with_python/blob/master/mglearn/plot_grid_search.py)

line 20: 
    results = pd.DataFrame(grid_search.cv_results_)[15:]
line 37-38:
    plt.xticks(range(len(results)), [str(x).strip("{}").replace("'", "") for x
                                     in grid_search.cv_results_['params']],

In line 37-38, an error occurs because the length of results and grid_search.cv_results_['params']] does not match.

Therefore, the line number 20 is corrected as follows.

    results = pd.DataFrame(grid_search.cv_results_)#[15:] comment out

And then, add the following rows to some suitable places (For example, after the 41st line.).

    plt.xlim(14.5, 36)

Thank you for your cooperation.

**Comment by wanghedy** [comment]
您的邮件已收到，我将会尽快处理，谢谢。王宇凝

**Comment by karitonov** [comment]
https://github.com/amueller/introduction_to_ml_with_python/issues/156#issue-1125129453

This issue is almost the same as above.

**Comment by karitonov** [comment]
https://github.com/amueller/introduction_to_ml_with_python/issues/156#issue-1125129453

The above method is better, so I will withdraw.
