### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cachedir'

### ISSUE THREAD

**Issue by muhammadjtareen** [amueller/introduction_to_ml_with_python#164]
I installed mglearn from pip by running 'pip install mglearn' but whenever I run 'import mglearn', I receive the following error: TypeError: __init__() got an unexpected keyword argument 'cachedir'

Is there any fix to this issue?

**Comment by embeddedpenguin** [comment]
Did you ever solve this? I'm getting the same issue

**Comment by embeddedpenguin** [comment]
I see the fix was posted here https://github.com/amueller/introduction_to_ml_with_python/issues/162#issuecomment-1264326158

**Comment by amueller** [comment]
should be fixed now in the repo as well.
