### ISSUE TITLE
Section 2.5 ("Summary and Outlook") seems to be blank

### ISSUE THREAD

**Issue by NeapolitanSuitcase** [amueller/introduction_to_ml_with_python#166]
I do not see any text or other content under "summary and outlook" in chapter 2 of the github etext. Does not seem intentional.

**Comment by wanghedy** [comment]
您的邮件已收到，我将会尽快处理，谢谢。王宇凝

**Comment by amueller** [comment]
There is no text in this repo, it is automatically generated from the book. So this is indeed "intentional".
