### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.six'

### ISSUE THREAD

**Issue by Abdulmalek98** [amueller/introduction_to_ml_with_python#172]
I use jupyterLite 

after 
%pip install mglearn
%pip install scikit-learn

if i execute the import mglearn return error :  No module named 'sklearn.externals.six'

![image](https://user-images.githubusercontent.com/39219895/216397560-c150452d-5076-4379-af14-9b567270cedd.png)

**Comment by amueller** [comment]
this should be fixed now. sorry for the slow response.
