### ISSUE TITLE
get_feature_names() -> get_feature_names_out()

### ISSUE THREAD

**Issue by yernero** [amueller/introduction_to_ml_with_python#178]
In chapter 7 code, ln 15
feature_names = vect.get_feature_names()
should be 
feature_names = vect.get_feature_names_out()
because deprecation warning

**Comment by yernero** [comment]
ln 26 too

**Comment by yernero** [comment]
ln 30 too

**Comment by yernero** [comment]
ln36 too

**Comment by amueller** [comment]
Indeed, the current version of the book was written for an older version, and since then we renamed the method for an API change. There's several other changes in the API.
