### ISSUE TITLE
Where is the data file for categorical feature example?

### ISSUE THREAD

**Issue by lingvisa** [amueller/introduction_to_ml_with_python#18]
See this code:

```
data = pd.read_csv("/home/andy/datasets/adult.data", header=None, index_col=False,
                  names=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income'])
```

Where should I get the 'adult.data' file? Thank you.

**Comment by amueller** [comment]
Hey. Sorry, it's in the ``data`` subfolder of this repository.

**Comment by amueller** [comment]
So if you are using the notebooks that come with this repository, you already have it and only need to change the path to ``data/adult.data``.

**Comment by lingvisa** [comment]
Right. I got it. One question regarding categorical feature. For example, gender(male, female), so I would represent as (1,0) for male or (0,1) female, according to the one-hot-encoding. Does it make a difference if I simply represent is male(1) and female(0), which is simpler. Generally, can I just single digit to represent a categorical feature, instead of a vector? If a feature has 5 categorical values, then each numerical value will be [0,1,2,3,4]?

**Comment by amueller** [comment]
You should keep reading on, the book explains that. For a binary feature like male/female, just a single feature would be ok. Actually, you can encode a categorical with ``m`` different values using ``m - 1`` different binary features (though I don't explain that in the book).
Using numerical values will be bad depending on the model you use. That I discuss in the chapter on feature engineering.

**Comment by lingvisa** [comment]
Got it. Thank you. Keep reading.
