### ISSUE TITLE
mglearn/load_boston issue 

### ISSUE THREAD

**Issue by epakhomov** [amueller/introduction_to_ml_with_python#183]
It's March 2024 and the mglearn still errors out because of the boston data set. It is not cool to sell not very cheap book like this. It has less value with the broken code. Degrading libraries is also not a good solution.

**Comment by wanghedy** [comment]
您的邮件已收到，我将会尽快处理，谢谢。王宇凝

**Comment by amueller** [comment]
Can you provide error? This should have been fixed in current mglearn. what version of mglearn are you using?

**Comment by epakhomov** [comment]
@amueller version is 0.2.0. I installed it today with pip install mglearn. The error snapshot enclosed. Thanks!
[error.txt](https://github.com/amueller/introduction_to_ml_with_python/files/14595724/error.txt)

**Comment by amueller** [comment]
Looks like I didn't update the version of mglearn in this repository, and you're using the one from this repository that you checked out with the notebooks, not the pip installed version. This duplication is a bit unfortunate, I was hoping it'll help people that are not familiar with the pretty confusing python packaging systems. If you delete the mglearn folder within your working directory, it should work. I'll update the package that's included in the repo now, so updating the repo afterwards should also work.

**Comment by amueller** [comment]
ok, this repo is now also updated. Let me know if you get it to work.

**Comment by epakhomov** [comment]
@amueller everything works now. Appreciate the quick response. Thanks!
