### ISSUE TITLE
Where is the aclImdb corpus

### ISSUE THREAD

**Issue by lingvisa** [amueller/introduction_to_ml_with_python#19]
```
tree -L 2 data/aclImdb

data/aclImdb [error opening dir]

0 directories, 0 files
```

Hi, Amueller, how to get this data? Thank you.

**Comment by amueller** [comment]
here: ai.stanford.edu/~amaas/data/sentiment/

Description is in the book ;)

**Comment by lingvisa** [comment]
Sadly, it is a dead link now. I clicked. Could you put it into the data/directory in this github repository, if you already have a copy?

**Comment by amueller** [comment]
that's not great. I'll see what I can do.

**Comment by amueller** [comment]
It's back up!

**Comment by lingvisa** [comment]
Great. Thank you.

**Comment by polosatyi** [comment]
Hey! http://ai.stanford.edu/~amaas/data/sentiment/ is a dead link again. @amueller could you help, please?

**Comment by amueller** [comment]
@polosatyi it's up now.

**Comment by polosatyi** [comment]
@amueller Thank you!
