### ISSUE TITLE
Error with mglearn.tools.visualize_coefficients()

### ISSUE THREAD

**Issue by Coxtox** [amueller/introduction_to_ml_with_python#21]
Hi, 

When I try to to observe important trigram features of my model with this code : 
`mask = np.array([len(feature.split(" ")) for feature in feature_names]) == 3
mglearn.tools.visualize_coefficients(coef.ravel()[mask],feature_names[mask], n_top_features=40)`

I have this error and I don't understand why ..
`ValueError: incompatible sizes: argument 'height' must be length 80 or scalar`

Do you have an idea ?

**Comment by amueller** [comment]
hey. I think coef and feature_names have different length. Maybe you updated one of them for a new model, but not the other?

**Comment by Coxtox** [comment]
Sorry for the late. I test to print the length of them but they have the same...
`print(len(feature_names))
print(len(coef.ravel()))`
I don't see why ..

**Comment by amueller** [comment]
What are ``coef.ravel()[mask]`` and ``feature_names[mask]``?
Or maybe better: when the error is thrown, what are the values of the variables in the call and what are their lengths?

**Comment by Coxtox** [comment]
oh ! the length of `coef.ravel()[mask]` and `feature_names[mask]` is 22. And I specify `n_top_features=40` .. 
I can display max 22 features, right ?
Thanks for your speed !!

**Comment by Coxtox** [comment]
Juste a question. In your examples, you return best cross-validation score. Can we calculate error on our sample test. I try with :
 `grille=grid.fit(text_train, Y_train)
y_pred = grille.predict(text_test)
from sklearn import metrics
#matrice de confusion
print("matrice confusion")
print(metrics.confusion_matrix(Y_test,y_pred))
#succès en test
print("score accuracy")
print(metrics.accuracy_score(Y_test,y_pred))`
But the accuracy score is equal to 0 ...

**Comment by amueller** [comment]
there are 2 * n_top_features displayed so it would make sense to specify 11. Otherwise the top and bottom 22 are the same ;)

**Comment by amueller** [comment]
check out the formating guide for code formatting. I fixed it for you ;)

**Comment by amueller** [comment]
The piece of code you provided looks correct. Btw, ``grille`` is the same as ``grid``, and you could do ``gille.score(text_test, Y_test)`` to get the accuracy. Whats the score on the training set? What does the confusion matrix look like?

**Comment by Coxtox** [comment]
`grille.score(text_test, Y_test)` returns 0.0
The validation score is equals to 80%. When I test ``grille.score(text_train, Y_train)` it was equals to 0.98.
When i print my confusion matrix, it was an unusual structure : 
`[[ 0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  0 23]
 [ 0  0  0  0  0  0  0  0  0  0  1 31]
 [ 0  0  0  0  0  0  0  0  0  0  0 34]
 [ 0  0  0  0  0  0  0  0  0  0  1 18]
 [ 0  0  0  0  0  0  0  0  0  0  3 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]`

**Comment by amueller** [comment]
Your classes are very imbalanced. Your model nearly always predicts the last class. If your training score is high, there is either a problem with how you represent the data, or you are overfitting.
Sorry, I can't really help you with debugging your model more than that, maybe try stackoverflow.

**Comment by Coxtox** [comment]
Thanks for your advice !
