### ISSUE TITLE
Broken mglearn figures for crossvalidation

### ISSUE THREAD

**Issue by joaquinvanschoren** [amueller/introduction_to_ml_with_python#23]
Chapter 5 shows 2 CV procedures that are broken in mglearn:

mglearn.plots.plot_shuffle_split() doesn't return a valid figure

mglearn.plots.plot_group_kfold() doesn't exist. There is a plot_label_kfold(), but it looks like it got mangled in a PR. If you change 'labels' to groups on line 22 it works.

**Comment by amueller** [comment]
thanks! Will hopefully fix soon ;) PR welcome!

**Comment by joaquinvanschoren** [comment]
in my version I also changed the name to plot_group_kfold(). Do you want that?

**Comment by amueller** [comment]
yes please.

**Comment by joaquinvanschoren** [comment]
ok, submitted

**Comment by joaquinvanschoren** [comment]
Not sure if it should be closed, there is an issue with 
mglearn.plots.plot_shuffle_split()

**Comment by amueller** [comment]
Right, thanks

**Comment by amueller** [comment]
should be fixed.
