### ISSUE TITLE
coefficients ckecking fail

### ISSUE THREAD

**Issue by rickiepark** [amueller/introduction_to_ml_with_python#25]
Line 26 in tools.py.
`if len(coefficients) != len(feature_names):`
But `coefficients` is 2d array, it should be
`if len(coefficients[0]) != len(feature_names):`

**Comment by amueller** [comment]
Thanks for pointing that out.

The function only really works for binary classification. I guess I'm passing ``coef_.ravel()`` to it sometimes?

I think the right fix would be to check whether ``coef_.ndim == 1 or coef_.shape[1] == 1``, error otherwise, and call ``ravel()``.

**Comment by rickiepark** [comment]
Yes, I think only binary task of the book. :-)
Your suggestion is great. 👍

**Comment by amueller** [comment]
should be fixed now :)
