### ISSUE TITLE
mglearn.plots does not works

### ISSUE THREAD

**Issue by rameshvishnoi90904** [amueller/introduction_to_ml_with_python#26]
mglearn.plots.plot_knn_classification(n_neighbors=3) open and instantly closes graph

**Comment by amueller** [comment]
In what environment? Can you open other plots? I figure you're not using jupyter? This was meant to be used from jupyter. Are you in interactive mode? I don't think there's a ``plt.show()`` in that function.

**Comment by rameshvishnoi90904** [comment]
I am not using jupyter. I am coding in my local machine (Mac). I will try jupyter, If not then is there any way to render plots in local machine?

**Comment by amueller** [comment]
Well how are you using it? In a script? In IPython? Can you use matplotlib at all?

**Comment by rameshvishnoi90904** [comment]
I Installed jupyter and enabled matplot
