### ISSUE TITLE
have to repeatedly run %matplotlib notebook to get plots

### ISSUE THREAD

**Issue by eliot1785** [amueller/introduction_to_ml_with_python#29]
I'm guessing this isn't an issue with the book per se, but I'm getting it going through the examples in Chapter 2 (pasting them in to Jupyter). I find that I need to rerun my imports frequently to get the plots to show. In the first cell I have:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display
%matplotlib notebook

and I basically have to go back and rerun that before each cell with a plot for some reason. Any idea what could be wrong?

**Comment by amueller** [comment]
If you use matplotlib notebook, any plot command will update previously
created figures unless you create a new figure. So my guess is that you
keep updating earlier figures so you don't see any new plots showing up.
You can either use plt.figure() before each new plot or use matplotlib
inline.

**Comment by eliot1785** [comment]
This was exactly the issue. Changing it seems to work. Thanks!

**Comment by eliot1785** [comment]
Thanks. Closing.
