### ISSUE TITLE
scikit-learn version

### ISSUE THREAD

**Issue by tpcarneiro** [amueller/introduction_to_ml_with_python#3]
The notebooks were written using the version 0.18.dev of scikit-learn and don't work with the latest (non dev) version of the package (0.17.1). The problem is that the 0.18.dev do not seems to be available for windows, which I’m unfortunately using right now.
I have edited some scripts in order to make the notebooks work and I intend to make a pull request for these changes later on.

**Comment by amueller** [comment]
Hey.
You can install the dev version by compiling yourself. There is now 0.18-rc available for windows on pipy.
You can install it with  ``pip install scikit-learn==0.18.rc2``
If you are using conda/anaconda, make sure that you uninstall any previous installation of scikit-learn first.
We will do a final release of scikit-learn 0.18 in about a week.

Best,
Andy

**Comment by tpcarneiro** [comment]
Hi, Mueller! 
Thank you very much for your answer, the tip for the RC version of scikit-learn worked perfectly! 
I was trying to compile the dev version from source, but I was having a lot of trouble. 
Now the notebook is running nice and smooth without any changes in the code, so I guess it's better to close the issue.
Thank you again and I'm sorry for bothering.

Regards,
Tiago.

**Comment by usakg** [comment]
Hi,
I thank you for your time to put up codes here and great book you have written(introduction_to_ml_with_python).
I am new to data science and don't have much of a computer science background. Since my professor offered to follow your book, there are some issues that I am dealing with(ex: cross_validation was one of them). Also, you have mentioned above try to change the version of scikit-learn to older ones.

My suggestion is: is there any way you can type out the reported issues with it's solutions? 
For example: sklearn.model_selection(your version) ==(equal to) sklearn.cross_validation(new version) as such.

My real issue is I could not find mglearn(NameError: name 'mglearn' is not defined) on internet or I did a bad research.

I assume you must be very busy, and I cannot ask for much for what you have already done for us(ambitious people). Any help would be appreciated.

Million Thanks,

**Comment by tpcarneiro** [comment]
Hi @usakg,
The deal with the scikit-learn is that you need the newer version of the framework, not the older ones. Like @amueller replied to me, I sugest you to install the 0.18.rc2 (see @amueller reply above) version that is now available throw the pip utility. This update solved all of my problems with the libraries.
About the "mglearn", this is module developed by the author himself and it's available along with the notebooks. If you look at the root of the repository you'll see a folder named "mglearn". In order to it word properly you only need to execute the notebooks from the same path as this folder.

Hope that my reply will help you.
Regards!

**Comment by amueller** [comment]
@usakg Scikit-learn version 0.18 will be released today or tomorrow, which should make installation much easier. Sorry things were a bit tricky to you as the early adopters.

Can you tell me how you are trying to run the code using mglearn? If you are running just the notebooks, there shouldn't be a problem.

**Comment by usakg** [comment]
Hello Mr. @tpcarneiro, 
Thanks for your comments, and helping me out.
I have seen Mr. @amueller's reply above, but I have not made any new version updates. Well...I was going to say it didn't work, but I tried second time and worked, I am happy. 👍 

Hello Mr. @amueller ,
I thank both of you and Mr. @tpcarneiro for quick replies, and I felt great that I am not alone here, and I can get help from you guys.
Yes, I was following the book and executing examples given there until I found github version. It's great that you have published here and it's easy to follow every line of the code in more details.
Kind Regards!

**Comment by ralphammer** [comment]
Dear Andreas,
I am new to python and try to get the examples in your (excellent) book up and running. I have installed anaconda but still need to install your mglearn-folder. And here comes an embarrassingly newby question: Where exactly do I put this folder in order to use it?

**Comment by amueller** [comment]
@ralphammer I'm glad you like the book.
For new questions, please open a new issue ;)

If you download the whole repository here, which includes the notebooks, the notebooks should just run. The folder that contains the notebooks also contains mglearn, so downloading this folder anywhere and opening the notebooks with jupyter should "just work".

If you are doing that and having trouble, please let me know.

If you want to use the mglearn functions outside of this particular folder, you need to tell python where to look for it, for example by doing ``export PYTHONPATH=$PYTHONPATH:<whereveritis>`` (without the <>). That works on Linux and OS X.

You can also check out this: https://support.enthought.com/hc/en-us/articles/204469160-How-do-I-set-PYTHONPATH-and-other-environment-variables-for-Canopy- (which also has instructions for windows).

Learning how to set the python path is important. You can also cheat and do ``pip install mglearn``. That will not get you the notebooks that are in this repository though.

**Comment by amueller** [comment]
Closing this issue as 0.18 is out :)

**Comment by davified** [comment]
For anyone still facing this issue of not being able to install `mglearn` with anaconda, just do the following:
1) clone this repo (if you haven't already done so)
2) copy the `mglearn` folder and `preamble.py` into the folder where you're running your jupyter notebooks (I have my own separate folder for the jupyter notebooks that I make when following this book)
3) before using mglearn, include `from preamble import *` in your jupyter notebook.

This should work.

**Comment by YurimarL** [comment]
Hi,
I'm new at this.  I'm having the _NameError: name 'mglearn' is not defined_ message once I got to **In [23]** of the book.  I have downloaded anaconda from http://store.continuum.io/cshop/anaconda/.  I have opened jupyter-notebook through the terminal which opened my home directory. Also, I have downloaded the _mglearn_ folder and added it to my home directory to see if it works but it doesn't.  I'm using the scikit-learn version: 0.19.1

What can I do to make It work? I'll appreciate any help.

**Comment by amueller** [comment]
try running ``! pip install mglearn`` in the notebook.

**Comment by YurimarL** [comment]
Thanks for your prompt response.  I have also try it but I got a permissionError: [Errno 13] Permission denied

**Comment by amueller** [comment]
Maybe check out this blog post:
http://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

What operating system are you on?

**Comment by amueller** [comment]
you can also just copy the mglearn folder into the folder that your notebooks are in.

**Comment by YurimarL** [comment]
Thanks I will check the blog post.  I had copy the mglearn folder but doesn't work either. I'm using Ubuntu.

**Comment by amueller** [comment]
if you get that error on Ubuntu it means your anaconda was installed by root, which is not a great idea usually.

**Comment by OfficialFreak** [comment]
Hey amueller, I used your book too and i've come to In[23] but i got the same Error as YurimarL. Except when I type in ! pip install mglearn in the notebook everything says its 'satisfied with the version' but it still says mglearn is undefined. I hope you can help

**Comment by amueller** [comment]
@OfficialFreak have you checked out the link I posted above? http://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by OfficialFreak** [comment]
Oh wait, im sorry, i've bothered you I forgot to import mglearn :D

**Comment by amueller** [comment]
@OfficialFreak glad you figured it out :)
If anyone else  has any issues, please open a new issue with a full description. Locking this as it goes off-topic.
