### ISSUE TITLE
'mglearn.datasets' has no attribute 'DATA_FOLDER'

### ISSUE THREAD

**Issue by kohaugustine** [amueller/introduction_to_ml_with_python#30]
Hi,

I have just cloned your repository and when I ran the notebook 02-supervised-learning, and hit the cell that contains the following code:
```
import os
ram_prices = pd.read_csv(os.path.join(mglearn.datasets.DATA_FOLDER, "ram_price.csv"))

plt.semilogy(ram_prices.date, ram_prices.price)
plt.xlabel("Year")
plt.ylabel("Price in $/Mbyte")
```
I get this error.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-121-e843eddf09a9> in <module>()
      1 import os
----> 2 ram_prices = pd.read_csv(os.path.join(mglearn.datasets.DATA_FOLDER, "ram_price.csv"))
      3 
      4 plt.semilogy(ram_prices.date, ram_prices.price)
      5 plt.xlabel("Year")

AttributeError: module 'mglearn.datasets' has no attribute 'DATA_FOLDER'
```
In the source file of datasets.py, I do not see any variable called `DATA_FOLDER`. Could this be another variable that needs to be updated?

Thank you.

**Comment by amueller** [comment]
It should be DATA_PATH, I'll fix the issue.

**Comment by amueller** [comment]
Actually, let me check the book.

**Comment by amueller** [comment]
I fixed the notebooks to have ``DATA_PATH``. You can either pull from the repository or just fix locally. Thanks for reporting and sorry for the inconvenience.

**Comment by kohaugustine** [comment]
thank you! It works now! Closing the issue.
