### ISSUE TITLE
"given enough data, ridge and linear regression will have the same performance"

### ISSUE THREAD

**Issue by eliot1785** [amueller/introduction_to_ml_with_python#31]
Is this strictly true (pp 54-55)? I am a beginner, but ridge has an artificial constraint imposed on the coefficients while linear regression does not. Therefore I would have expected linear regression performance to eventually exceed that of ridge, since regularization puts a cap on how good ridge can get. Just curious if this is wrong.

**Comment by amueller** [comment]
I am assuming here that you adjust the penalty alpha in ridge. If there is enough data, the penalty that is selected will become very small and have little or no effect.

**Comment by amueller** [comment]
I guess in this particular example I'm not adjusting the penalty, because I'm running a single alpha. You are right, with a constant alpha ridge might be worse if the penalty is too high.

**Comment by eliot1785** [comment]
Thanks, that makes sense.
