### ISSUE TITLE
Type Error issue on discrete_scatter()

### ISSUE THREAD

**Issue by takeshi-a** [amueller/introduction_to_ml_with_python#32]
Hi Andreas,

Now I'm trying to trace your repo to learn how to use scikit-learn. In the 4th row of the 2nd cell of the notebook, "02-supervised-learning.ipynb", discrete_scatter() are called to plot the blob data. 

```python
mglearn.discrete_scatter(X[:, 0], X[:, 1], y) 
```

However I was trapped by an error which says, "TypeError: 'Cycler' object is not callable". It seems that current_cycler() which is called in the 80th line in the file "plot_helpers.py" is wrong.

```python
current_cycler = mpl.rcParams['axes.prop_cycle']

for i, (yy, cycle) in enumerate(zip(unique_y, current_cycler())):
```
I guess current_cycler is not callable since it is defined as rcParams object in the previous line and the parentheses '()' should be removed. It worked when I removed them and run the program in my laptop.

I hope my point makes sense.

Takeshi

**Comment by amueller** [comment]
Try to upgrade the "cycler" library, you have a very specific early
release, all later versions should work. And/or update matplotlib.

**Comment by takeshi-a** [comment]
Thanks. According to your direction, I've just updated the "cycler" library and it worked well. The versions was updated from 0.9.0 to 0.10.0. 

The "cycler" documentation helped me to see the function.
[http://matplotlib.org/cycler/](http://matplotlib.org/cycler/)
