### ISSUE TITLE
reshape is no longer supported (page 246 / Chapter 4)

### ISSUE THREAD

**Issue by eliot1785** [amueller/introduction_to_ml_with_python#33]
Cell 51 on page 246 (Chapter 4) will exit with an error for anybody running Pandas versions less than ~11 months old. This is because reshape was deprecated on Index objects for some reason. 

Here is the Pandas change: https://github.com/pandas-dev/pandas/commit/084ceaee135627680f4dd00115c3d6c7d930a22d

The actual error is: "NotImplementedError: reshaping is not supported for Index objects"

**Comment by eliot1785** [comment]
Ok, it looks like this code is changed here in Github (pasted below). However for me at least this gives a different error: "ValueError: invalid literal for int() with base 10: '2015-08-01 00:00:00'"

I am using a recent version of Anaconda (downloaded under 2 months ago).


# extract the target values (number of rentals)
y = citibike.values
# convert the time to posixtime using "%s"
X = citibike.index.strftime("%s").astype("int").reshape(-1, 1)

**Comment by amueller** [comment]
hm so the ``strftime("%s")`` doesn't work? I remember there was some problem with that. I'll look into it.

**Comment by amueller** [comment]
@eliot1785 could you please provide your version of pandas? You can do that with
```python
import pandas
print(pandas.__version__)
```
It should be
```python
X = citibike.index.astype("int64").values.reshape(-1, 1) // 10**9
```
Let me know if that doesn't work.

**Comment by eliot1785** [comment]
Hooray, that works for me!

Since you asked, I am running Pandas 0.19.2

**Comment by amueller** [comment]
cool. Should be fixed in the new print of the book.
