### ISSUE TITLE
many support vectors in figure 2-42

### ISSUE THREAD

**Issue by eliot1785** [amueller/introduction_to_ml_with_python#34]
I hope this is a reasonable question. Figure 2-42 (Out[86] in the notebook for chapter 2, page 102 in the PDF) is odd, in that 100% of the points are support vectors in the top row and rightmost column. From my limited understanding I would have expected the number of support vectors to be lowest in the top row, and increase in the second and third rows as complexity is added.

(I would not have expected the number of support vectors to vary with gamma, since it seems like gamma is considered after SV's are already determined)

Just wanted to make sure this is expected, and perhaps ask you for an explanation. Thank you.

**Comment by amueller** [comment]
Hey.
Smaller C means more regularization means more support vectors. Basically regularization limits the influence that each point can have, and therefore more support vectors are required. This is a common question though, I'm not sure I can explain it well without going into the math behind it.
Alternatively, more regularization means you allow more points in the margin. With no regularization (C=inf, hard margin) you allow no data points in the margin. regularization relaxes this constraint, and the smaller C the wider the margin but the more data points lie within the margin. All the data points in the margin are always support vectors.
Also check out https://github.com/scikit-learn/scikit-learn/pull/8957
and https://github.com/scikit-learn/scikit-learn/issues/7955

**Comment by eliot1785** [comment]
Thanks, this is helpful. I didn't realize scikit-learn had a whole essay dedicated to these parameters, will read that.

**Comment by amueller** [comment]
@eliot1785 scikit-learn has a lot of good stuff in the user guide. The book is intended as a more structured introduction, but you should definitely check out the user guide and examples!
