### ISSUE TITLE
images/ directory is missing

### ISSUE THREAD

**Issue by blinkeye** [amueller/introduction_to_ml_with_python#35]
which causes

1. a minor issue in _01-introduction.ipynb_ where the static image should be displayed: 
`### A First Application: Classifying iris species
![sepal_petal](images/iris_petal_sepal.png)`

2. a minor issue for _02-supervised-learning.ipynb_ where the static image should be displayed:
`![model_complexity](images/overfitting_underfitting_cartoon.png)`

3. a **bigger** issue in _03-unsupervised-learning.ipynb_ where an image should be written to:
`plt.savefig("images/03-face_decomposition.png")
plt.close()`
and the Notebook execution stops if the directory _images/_ does not exist.

`mkdir images` obviously solves the problem for _03-unsupervised-learning.ipynb_, but I think the directory should be in the git repo in the first place (along with a few static images used in the notebooks).

**Comment by blinkeye** [comment]
4. a minor issue for _6-algorithm-chains-and-pipelines.ipynb_ where a static image should be displayed:
`![pipeline_illustration](images/pipeline.png)`

**Comment by amueller** [comment]
thanks for the report. wow, I hadn't noticed that. Can you check if it's fixed now?

**Comment by blinkeye** [comment]
Perfect, thanks!
