### ISSUE TITLE
README.md contains wrong Conda graphviz installation instructions

### ISSUE THREAD

**Issue by blinkeye** [amueller/introduction_to_ml_with_python#38]
In 

> Installing packages with conda:

you specify:

`$ conda install numpy scipy scikit-learn matplotlib pandas pillow graphviz graphviz-python
`

but `graphviz-python` does not exist and should be `python-graphviz`:

`$ conda install numpy scipy scikit-learn matplotlib pandas pillow graphviz python-graphviz
`

**Comment by amueller** [comment]
fixed in #39
