### ISSUE TITLE
Introduction should include setup

### ISSUE THREAD

**Issue by johnciliberti** [amueller/introduction_to_ml_with_python#4]
You should add a section to chapter 1 that either gives instructions for getting everything you need set or point to a Wiki page or something that provides the instructions.

Currently you only have a list of some of the libraries. For example you say we need scipy but neglect to mention that you allow need to installed Pillow which is not included with scipy but is required for the imread function you are using in your plotting library. You should also provide links and instructions for setting up and using Jupyter Notebook so that people can follow along and see the charts inline as shown in the book.

**Comment by amueller** [comment]
Hi @johnciliberti. That's a great idea.
Unfortunately this is too late for the printed book, but we can certainly add this here and maybe in the e-book. I think the book mentions installing anaconda, which comes with everything you need. But I should make that more explicit.

**Comment by Amanda-Clark** [comment]
Not sure if this belongs here, but also to be able to import mglearn on my system (Python 3.4 on OS X 10.10) I had to pip install cycler in addition to specifying Pillow 2.6.0.

**Comment by amueller** [comment]
@Amanda-Clark hm that is interesting. How did you install matplotlib? It should have cycler as a dependency.

**Comment by Amanda-Clark** [comment]
I'm sorry its been ages since I've installed it :(

**Comment by amueller** [comment]
I added instructions to the readme. And @Amanda-Clark you should probably update matplotlib.

**Comment by yinleon** [comment]
Hi @amueller, when you display decision tree dot files in your ch_2 notebook, is `display()` originating from `from IPython.display import display`?

Can't get `graphviz.Source(dot_graph)` to render in my notebook. I am using graphviz `0.5.1` and IPython `5.1.0`. I followed the conda _then_ pip install of graphviz from the readme.

**Comment by amueller** [comment]
yes, it's ``from IPython.display import display``.
If you just put ``graphviz.Source(dot_graph)`` into a cell and evaluate, you should get the graph as the jupyter representation. I added the display to the book so that it's clear we're doing it for the output.

**Comment by yinleon** [comment]
I get an empty out[ ]:
![screen shot 2016-10-26 at 6 14 55 pm](https://cloud.githubusercontent.com/assets/7376699/19747191/409359e2-9ba8-11e6-9c44-38dd6b160673.png)
I couldn't find a similar issue online, but I would recreate it on my home and work computer.

**Comment by amueller** [comment]
That's odd. Try using the ``render`` method? http://graphviz.readthedocs.io/en/latest/manual.html#using-raw-dot

**Comment by yinleon** [comment]
It was an issue with a Dot dependency. If anyone else has a similar problem I found this StackOverflow <a href="http://stackoverflow.com/a/17761170/5094480">post</a>.

**Comment by amueller** [comment]
thanks @yinleon. I'm kind of surprised, as ``conda`` should manage it's own dependencies... but who knows...

**Comment by amueller** [comment]
I'm closing this as I added instructions to the readme.
