### ISSUE TITLE
07-working-with-text-data.ipynb: missing data/aclImdb/train directory

### ISSUE THREAD

**Issue by blinkeye** [amueller/introduction_to_ml_with_python#41]
The notebooks starts with a tree and cleanup command which fail on a up-to-date Ubuntu 16.04 Xenial:
```
Types of data represented as strings
Example application: Sentiment analysis of movie reviews
In [2]:

!tree -dL 2 data/aclImdb
/bin/sh: 1: tree: not found
In [3]:

!rm -r data/aclImdb/train/unsup
rm: cannot remove 'data/aclImdb/train/unsup': No such file or directory
```
The missing tree package problem is fixed by:
`sudo apt install tree`

The real problem follows a bit later on the In[4] code snippet:
```
from sklearn.datasets import load_files

reviews_train = load_files("data/aclImdb/train/")
# load_files returns a bunch, containing training texts and training labels
text_train, y_train = reviews_train.data, reviews_train.target
print("type of text_train: {}".format(type(text_train)))
print("length of text_train: {}".format(len(text_train)))
print("text_train[6]:\n{}".format(text_train[6]))
```
which throws:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-a724a25f6c25> in <module>()
      1 from sklearn.datasets import load_files
      2 
----> 3 reviews_train = load_files("data/aclImdb/train/")
      4 # load_files returns a bunch, containing training texts and training labels
      5 text_train, y_train = reviews_train.data, reviews_train.target

/home/blinkeye/anaconda3/lib/python3.6/site-packages/sklearn/datasets/base.py in load_files(container_path, description, categories, load_content, shuffle, encoding, decode_error, random_state)
    199     filenames = []
    200 
--> 201     folders = [f for f in sorted(listdir(container_path))
    202                if isdir(join(container_path, f))]
    203 

FileNotFoundError: [Errno 2] No such file or directory: 'data/aclImdb/train/'
```

**Comment by amueller** [comment]
thanks for the report.
Did you download and unzip the data?

The tree call requires the ``tree`` ubuntu package. Maybe I should just remove the command and just output the tree?

**Comment by blinkeye** [comment]
Ah, I see. You mean [aclImdb_v1.tar.gz](http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz) which is mentioned in the PDF/book but not in the in _07-working-with-text-data.ipynb_.

Maybe you want to add a comment in the Jupyter notebook like:

```
cd introduction_to_ml_with_python/data
wget http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
tar xvzf aclImdb_v1.tar.gz
```

**Comment by amueller** [comment]
Well, the code is meant as a supplement to the book. I can't guarantee any of it makes sense without the book. For that, I would have to maintain everything twice, that's not really feasible.

I am trying to have these as much as sync in possible. There is really no text in the notebooks because the way I generate these notebooks from the book is by stripping out the text. Having any extra text in the notebooks would mean I would have to take special care of that whenever I'm updating anything in the book, and handling diffs with jupyter notebooks is really tricky.

I would rather not add these commands in a code cell, as they are very POSIX specific. Though the same is true for the ``tree`` command. I think the best solution might be to add a POSIX specific code cell and mention that clearly with alternative instructions for windows.
However, that really needs a fix in the book, not in these notebooks that are generated from the book.
Can you maybe open an errata? That makes it a bit easier for me to track.

**Comment by amueller** [comment]
fixed in the next print. I'll update this repo tomorrow.

**Comment by linis28** [comment]
Hola, no he podido cargar y leer el archivo, por favor, puede darme una ayuda

**Comment by linis28** [comment]
Hola he traducido, su libro, me gustaría saber si le interesa para enviar

**Comment by linis28** [comment]
Lo ejecuté  en  Spyder

**Comment by linis28** [comment]
Pero no he podido correr data de texto

**Comment by amueller** [comment]
@linis28 can you please open an issue with the details of the error you ran into? Did you download the data?
Also, it would be great if you could ask in English, I don't speak Spanish.

**Comment by linis28** [comment]
Hello, Mr.   Andreas C. Müller

  A greeting with much respect, I beg your pardon for my daring to write to
you.

But I really want to communicate to you, that I have translated into
Spanish your Book entitled: Introduction to Machine Learning with Python (A
Guide for Data Scientists), and I have transcribed it in latex, I’ll finish
it, just need some alphabetical index in the last chapters, and the
preface.

The First Chapter is attached.

You may be interested in publishing it or giving permission to do so.  I
appreciate your opinion on this.

Yours truly,

 Profesor,   Linis Guerrero

**Comment by linis28** [comment]
Sorry, what happened was that the data had not downloaded well, it had
errors. Problem solved.


Grateful

**Comment by amueller** [comment]
Glad you worked it out. Have you worked with O'Reilly on the translation? I think you need their permission mostly, though I think they'd be happy to work with you.

**Comment by bishowshr1** [comment]
wget http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz 
not working...

**Comment by amueller** [comment]
@bishowshr1 is it still not working? Maybe the server was down for a bit?
