### ISSUE TITLE
docker files to create a docker image with everything preconfigured 

### ISSUE THREAD

**Issue by blinkeye** [amueller/introduction_to_ml_with_python#46]
Hi Andreas

what would you think about providing a docker file for a reproducible environment in this repo? I've created the necessary docker files based on the official [continuumio/anaconda](https://hub.docker.com/r/continuumio/anaconda/) image(s). Both a **Python2.7** and a **Python3** based image can be created including the additional packages we need to run your notebooks.

Pull-requests follows shortly (tested on Ubuntu 16.04).

This allows for us (readers) to easily run your notebooks in a pre-tested and properly configured environment. The initial docker build command takes a while but once one has all the necessary images downloaded re-creating _your image_ takes a few seconds (if recreating the image is ever needed that is).

I'm currently binding your whole repo and files into the docker image which allows for git pull outside the container without re-creating the docker image. This means you may rename, change, delete and add new files without the need to adapt the docker files. All we (readers) need to do is pulling from this repo.

**Optional (next step):**
If you intend to actually provide a pre-configured docker **image** (not just the _Dockerfile_) yourself the following things might change:

1. you probably would want to package (e.g. snapshot/release) your notebooks from this repo into the docker image (hence having full control of the environment **and** the notebook versions)
2. you probably would want to pre-download the additional /data files in the image, see #41 

What do you think?

**Comment by amueller** [comment]
I think providing a docker file might be beneficial. I don't think I have the bandwidth to maintain a docker image.
Ideally I'd like to have the requirements of the book to be so easy to install that readers don't need docker. Ideally, after reading the book, they have a setup that they can use in the future.
It seems that installing spacy is not that easy, and there are some minor issues with graphviz.
I think it would be better to try to fix these issues upstream, for example by ensuring there's an up-to-date spacy package in the conda main distribution.

**Comment by amueller** [comment]
see https://github.com/ContinuumIO/anaconda-issues/issues/2649
