### ISSUE TITLE
where is the plot for figure 1-3

### ISSUE THREAD

**Issue by shouwei** [amueller/introduction_to_ml_with_python#47]
Hi there,

I am a fresh bird to machine learning and try to walk through the book to grasp a general idea.

But I did not find the plot code snippet for figure 1-3. The book writes:
"Figure 1-3 is a pair plot of the features in the training set. The data points are colored according to the species the iris belongs to. To create the plot, we first convert the NumPy array into a pandas DataFrame. pandas has a function to create pair plots called scatter_matrix. The diagonal of this matrix is filled with histograms of each feature:"

then followed an input command:
```python
In[24]:
# create dataframe from data in X_train
# label the columns using the strings in iris_dataset.feature_names iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
# create a scatter matrix from the dataframe, color by y_train
grr = pd.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o',
                            hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)
```
then the figure 1-3 comes out. Would you please tell me which command we use to generate or plot figure 1-3?

Thank you so much!

**Comment by amueller** [comment]
Hey.
I'm not sure I understand your question. We are using the ``pd.scatter_matrix`` function that you quoted.
You can find the documentation of that in the [pandas docs](https://pandas.pydata.org/pandas-docs/stable/visualization.html#visualization-scatter-matrix).

**Comment by shouwei** [comment]
hi,
thanks for your reply.
My question is: after running the function pd.scatter_matrix, I did not get any plots, and also no any error.
I do not change anything just copy the code line by line.

**Comment by amueller** [comment]
you need to have
``%matplotlib inline``
in the notebook.

**Comment by shouwei** [comment]
here is the complete source code, would you please show me the mistake? It stored in demo1.py and executed with python3 demo1.py

import sys
print("Python version: {}".format(sys.version))

import numpy as np
print("NumPy version: {}".format(np.__version__))

import pandas as pd
print("pandas version: {}".format(pd.__version__))

import matplotlib
print("matplotlib version: {}".format(matplotlib.__version__))

import matplotlib.pyplot as plt
#plt.plot([1,2,3], [1,2,3])
# Generate a sequence of numbers from -10 to 10 with 100 steps in between
x = np.linspace(-10, 10, 100)
# Create a second array using sine
y = np.sin(x)
# The plot function makes a line chart of one array against another plt.plot(x, y, marker="x")
plt.plot(x, y, marker="x")
plt.show(block=True)

import scipy as sp
print("SciPy version: {}".format(sp.__version__))

import IPython
print("IPython version: {}".format(IPython.__version__))

import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))

import mglearn

from IPython.core.display import display

from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

print(iris_dataset['DESCR'][:193] + "\n...")

print("Target names: {}".format(iris_dataset['target_names']))

print("Feature names: \n{}".format(iris_dataset['feature_names']))

print("Type of data: {}".format(type(iris_dataset['data'])))

print("Shape of data: {}".format(iris_dataset['data'].shape))

print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

print("Type of target: {}".format(type(iris_dataset['target'])))

print("Shape of target: {}".format(iris_dataset['target'].shape))

print("Target:\n{}".format(iris_dataset['target']))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
grr = pd.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o', hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mgle

**Comment by amueller** [comment]
are you running this inside a jupyter notebook or from a script?
If you're running it in a script, you need to call ``plt.show()``, if you run it in a notebook, you need to do ``matplotlib inline`` in the beginning, as I mentioned.

Btw, you can format code as described here, with triple backticks followed by ``python``.
https://guides.github.com/features/mastering-markdown/

**Comment by shouwei** [comment]
@amueller wow, cool! I got it. Add plt.show() at then end of the script.
Thank you so much!

**Comment by amueller** [comment]
@shouwei glad it worked for you :)
