### ISSUE TITLE
01-introduction - ImportError: cannot import name plots

### ISSUE THREAD

**Issue by aanandhc** [amueller/introduction_to_ml_with_python#48]
`from preamble import *`

I get the following error message:
```
-----------------------------------------------------
ImportError         Traceback (most recent call last)
<ipython-input-51-4b76e7eb44e5> in <module>()
----> 1 from preamble import *

/Users/Aanandh/Desktop/Data Science/introduction_to_ml_with_python/preamble.py in <module>()
      3 import numpy as np
      4 import matplotlib.pyplot as plt
----> 5 import mglearn
      6 from cycler import cycler
      7 

/Users/Aanandh/Desktop/Data Science/introduction_to_ml_with_python/mglearn/__init__.py in <module>()
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 from .tools import discrete_scatter
      5 from .plot_helpers import ReBl

ImportError: cannot import name plots
```

**Comment by aanandhc** [comment]
Versions I'm using:

> Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
pandas version: 0.20.3
matplotlib version: 1.3.1
NumPy version: 1.8.0rc1
SciPy version: 0.13.0b1
IPython version: 5.4.1
scikit-learn version: 0.18.2

**Comment by amueller** [comment]
what's the content of
```
/Users/Aanandh/Desktop/Data Science/introduction_to_ml_with_python/mglearn
```
?

**Comment by amueller** [comment]
and can you try ``from mglearn import plots``

**Comment by aanandhc** [comment]
Everything in `/Users/Aanandh/Desktop/Data Science/introduction_to_ml_with_python` is cloned from github.

trying `from mg learn import plots` gives me this error:

> ----> 1 from preamble import *
> 
> /Users/Aanandh/Desktop/Data Science/introduction_to_ml_with_python/preamble.py in <module>()
>      15 plt.rc('axes', prop_cycle=(
>      16     cycler('color', mglearn.plot_helpers.cm_cycle.colors) +
> ---> 17     cycler('linestyle', ['-', '-', "--", (0, (3, 3)), (0, (1.5, 1.5))])))
>      18 
>      19 np.set_printoptions(precision=3, suppress=True)
> 
> /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.pyc in rc(*args, **kwargs)
>     197 @docstring.copy_dedent(matplotlib.rc)
>     198 def rc(*args, **kwargs):
> --> 199     matplotlib.rc(*args, **kwargs)
>     200 
>     201 
> 
> /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/__init__.pyc in rc(group, **kwargs)
>    1043             except KeyError:
>    1044                 raise KeyError('Unrecognized key "%s" for group "%s" and name "%s"' %
> -> 1045                                (key, g, name))
>    1046 
>    1047 def rcdefaults():
> 
> KeyError: 'Unrecognized key "axes.prop_cycle" for group "axes" and name "prop_cycle"

**Comment by amueller** [comment]
can you try updating your matplotlib? It looks like you're using the system python on MacOS. That might not be the best idea, as upgrading libraries might break your system. I'd recommend using a separate Anaconda environment for running the notebooks.

**Comment by aanandhc** [comment]
Downloaded and used anaconda - that fixed it. Thanks!
