### ISSUE TITLE
photos in chapter 3 coming out as green

### ISSUE THREAD

**Issue by eliot1785** [amueller/introduction_to_ml_with_python#50]
Do you know why the photos in Chapter 3 come out green when you run it in the notebook? In the PDF there are some green photos, but not all. When running the notebook myself the photos are all green.

**Comment by amueller** [comment]
This depends on the colormap. The green colormap is viridis (which I use when there are positive and negative entries in the image), the grey colormap is "gray" which  I use for images most of the time.
The top of chapter 3 has the line
``python
plt.rcParams['image.cmap'] = "gray"
```
which should set the default colormap to gray. It sounds like you might not have run that line.

**Comment by eliot1785** [comment]
Aaah yes - I did miss that because I jumped right in to the clustering section. This resolves it. Thanks for your help!!
