### ISSUE TITLE
Matplotlib warning regarding: mglearn.plots.plot_cross_validation() [Ch-5, In[2], p-254]

### ISSUE THREAD

**Issue by GaussEuler** [amueller/introduction_to_ml_with_python#56]
Respected Dr. Muller,
When I run this command, 'mglearn.plots.plot_cross_validation()', I get the following warning:
**_C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py:2648: MatplotlibDeprecationWarning: The *bottom* kwarg to `barh` is deprecated use *y* instead. Support for *bottom* will be removed in Matplotlib 3.0
  ret = ax.barh(*args, **kwargs)_**

Furthermore, the output is not clear i.e. all the 'training-data boxes' (the non-dark ones) after the first row do not appear. 
The same is the case when I run the command ['mglearn.plots.plot_cross_validation()'] that appears in the next page (In[7], page-257).
I just thought to let you know about this.

Sincerely,
Nikhilesh

**Comment by amueller** [comment]
which version of matplotlib are you using, and which version of mglearn? I think you need to update the mglearn code.

**Comment by amueller** [comment]
``mglearn.__version__`` should be '0.1.6'

**Comment by gaussEuler** [comment]
Thank you Dr. Muller for your reply.
My mglearn and matplot lib versions are:
mglearn.__version__
Out: '0.1.6'

matplotlib.__version__
Out: '2.1.0'

**Comment by amueller** [comment]
I can reproduce, it's an issue with matplotlib 2.1.0. I need to investigate.

**Comment by amueller** [comment]
See https://github.com/matplotlib/matplotlib/issues/9351 it will be fixed in matplotlib 2.1.1

**Comment by gaussEuler** [comment]
Thank you so much Dr. Muller for investigating this issue and for replying!
