### ISSUE TITLE
About: mglearn.plots.plot_cross_val_selection() [Ch-5, In[21], page-266]

### ISSUE THREAD

**Issue by gaussEuler** [amueller/introduction_to_ml_with_python#59]
Respected Dr. Muller,
Just for your information - when I run the following code from your book:
import mglearn
mglearn.plots.plot_cross_val_selection()

I do get the proper figure output, but I also get a warning which might be of interest to you:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: **FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True**
  warnings.warn(*warn_args, **warn_kwargs)

My sklearn and mglearn versions are as follows:
sklearn.__version__
Out: '0.19.1'

mglearn.__version__
Out: '0.1.6'

Thank you,
Sincerely,
Nikhilesh

**Comment by amueller** [comment]
Thanks for reporting, I fixed the warning in the current code a couple of days ago in 79a0be2b751d95c62199078f0e835db4135704f4 . It's a change in scikit-learn 0.19.1.

**Comment by amueller** [comment]
(it is of no consequence, other than that it'll break in 0.21)
