### ISSUE TITLE
Question about make_blobs(n_samples) [In[51] (page-288, Ch-5), ISBN# 978-1-449-36941-5]

### ISSUE THREAD

**Issue by GaussEuler** [amueller/introduction_to_ml_with_python#60]
Respected Dr. Muller,
I have been having hard time figuring out how to properly use cross-validation (especially, cross_val_predict) in lieu of the train_test_split() method used in In[51] (page-288, Ch-5) - once I can properly formulate the question, I shall ask you about it. Meanwhile, I have another question that concerns with the same code (In[51], page-288, Ch-5): the first two lines of that  code are:
**from mglearn.datasets import make_blobs
X, y = make_blobs(n_samples=(400, 50), centers=2, cluster_std=[7.0, 2], random_state=22)**

My question concerns with:  **n_samples=(400, 50)**, where, 400 implies negative class points and 50 implies positive class points (as stated in the book)
However, I could not find any reference of the class distribution in n_samples in your website where you define it (**https://github.com/amueller/mglearn/blob/master/mglearn/make_blobs.py**).  
[I am a newbie in terms of Python (whatever Python I have learned is by going through your codes from the book, one line at a time) and also programming in general. So, please forgive me if I am getting confused and asking you a stupid question]

Everywhere I have looked, the n_samples is designated as: **_n_samples=100_** [for example, or some other number, but not **_(100, 2)_** for instance]
If you can guide me to a general syntax for n_samples, I will greatly appreciate.

Thank you so much for all your help,
Sincerely,
Nikhilesh

**Comment by amueller** [comment]
I'm not sure I understand your question. Are you asking about the code or the documentation? The docstring is indeed not very precise. If you pass a tuple, it's the number of samples per class, if you pass an integer, this number is the total number divided equally among classes.

**Comment by gaussEuler** [comment]
Yes! Thank you! 
I was confused with the sklearn and mglearn versions of make_blobs. Also, your explanation above is much more clearer to me (as I am not that adept at Python) then the one mentioned in the mglearn website (mentioned above).
Thank you again so much Dr. Muller.
Sincerely,
Nikhilesh

**Comment by amueller** [comment]
No worries. Let's keep this open until I make the docstring better.

**Comment by gaussEuler** [comment]
Ok. 
Thank you again so much for clearing this issue.

**Comment by amueller** [comment]
will be fixed in the next print.
