### ISSUE TITLE
01-introduction.ipynb

### ISSUE THREAD

**Issue by shiva1387** [amueller/introduction_to_ml_with_python#62]
"from IPython import display" produces a  TypeError in the python version 3.6.0 in the ipython notebook. However, as as indicated in the book,  the commands when the import is performed as  "from IPython.display import display" .

**Comment by amueller** [comment]
Thanks, looks like I failed to make this fix in the github repo. Just pushed it.

**Comment by amueller** [comment]
fixed in the next print. You don't actually need to import display any more in newer versions of Jupyter.
