### ISSUE TITLE
Is this covered in your book?

### ISSUE THREAD

**Issue by OliverBarrett** [amueller/introduction_to_ml_with_python#64]
I ordered, but have not yet received your book, so I wanted to ask a basic question to make sure your book covers basic problems like this one.

While diving in, I was thinking of looking at linear regression for a set of error data. These data have two columns: (1) "ErrorDate" -> week number (of year), and (2) "ErrorCount" (how many errors did the system have in that week).

I would imagine these data are pretty noisy (random), but who knows?

Anyway, I tried to load this data and do a basic LinearRegression fit test but got an error. (My pandas book has not arrived from the third-party seller either).

**"ValueError: Expected 2D array, got 1D array instead:"**

--
The code seems so simple, like it should work:

# Read CSV data into dataframe
thedf = pd.read_csv("Errors.csv", sep=",")

X_train, X_test, y_train, y_test = train_test_split(
    thedf['ErrorCount'], thedf['ErrorDate'], random_state=0)

print (ussdf.head())

**>>>> Prints: 
   ErrorDate  ErrorCount
0          1          80
1          2         118
2          3         249
3          4         397
4          5         159**

So far, so good..

-----
But, the shape is apparently wrong:

print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

**>>>> Prints: 
X_test shape: (13,)
y_test shape: (13,)**

-- 

So, I see the shape is the problem, but I'm wondering if your book covers this basic Pandas set up or if I need to wait for my Pandas book to arrive and hope it covers how to "resize" (I think) the data frame?

Or, is this a case where I need that more introductory book you mentioned as anyone using your book would have this basic pandas knowledge?

It can be frustrating climbing that learning curve...

Thanks,

**Comment by amueller** [comment]
I'm not going through pandas details in my book. You extract a column from a dataframe, which is a series. Scikit-learn expects a dataframe or a 2d numpy array. Easiest way is to convert to a numpy array and reshape:
```python
X = X.values.reshape(-1, 1)
```

**Comment by amueller** [comment]
You can also ask basic questions like this on stackoverflow, or check out the online docs of numpy, pandas and scikit-learn.

**Comment by OliverBarrett** [comment]
Wow, when a simple (probably the simplest) use-case isn't covered in an intro book, that means your book is not actually for me to begin with. Your stated assumptions that no prior knowledge being necessary seems in question.

I spent all day trying to get two-dimensional data into a format where I could call the "fit" method. Never got it working.  Posted messages on Stack. Nothing.

Searched for a simple example showing how to import two columns from a spreadsheet (read.csv) and do simple linear regression. Nope.

Why wouldn't an introductory book cover such a simple starting and obvious use-case?

Hopefully my Pandas book will help when it gets here sometime this week.

Thanks

**Comment by amueller** [comment]
No prior knowledge about machine learning, not no prior knowledge about python. (Does it say anywhere no prior knowlege of python? That would be quite misleading and I should change it).

I think the book by Jake that I mentioned might be a better start for you, and it's free online! you can always come back to mine afterwards.

**Comment by OliverBarrett** [comment]
I am fine with programming trees, recursion, and all that. Been there, done that.

It's learning to use "other peoples'" libraries (which are in advanced state of development) that can be difficult. In some ways (maybe not with machine learning algorithms), it's almost easier if you write all the code yourself. Then you're not stuck trying to figure out how to make some library input routine happy.

I looked at Jake's book link before, but as I saw it, it's just a bunch of those maddening Jupiter notebooks.

If there's a (readable) PDF or something like that, I would definitely download and read that first.

I see that there's a Jake (same author as the Padas book that will arrive here this week) who has a three hour lecture on Youtube. That might be better if there's no PDF of his book.

Thanks,

**Comment by amueller** [comment]
If you want to enter data science in python, I would encourage you to come to terms with notebooks, or you'll have a hard time. I think can not publish pdfs for free, but you can also buy his book. I'm talking about jake vanderplas who I'm sure has many hours on youtube. I don't think he wrote a pandas book, though.

**Comment by OliverBarrett** [comment]
This may be my baggage with 20+ years in development, but professional developers use IDEs not notebooks. :)

**Comment by amueller** [comment]
I only have about 10 years on IDEs but how about using the right tool for the right job? ;)

**Comment by OliverBarrett** [comment]
I guess I'm already thinking ahead to deployment. Can you deploy a _notebook_ to a REST-based service like Flask? That's why I use an IDE, other than habit, i guess. I'm also used to the whole IDE environment with debugging, refactoring, etc. The Notebook thing seems like a huge step backwards in time.

In any case, what you're saying is that if I download and use Anaconda, reading your and other books (as well as doing this ML stuff) will be much simpler as that's the way people do ML stuff by default in the Python world?

**Comment by amueller** [comment]
@OliverBarrett yes, it will be much simpler. And while it might be technically possible to deploy a notebook, I don't think anyone would recommend that (except in very very special cases). Definitely use your IDE for writing a web service.

Notebooks are good in an educational setting and for exploratory data analysis, in particular because of the immediate feedback. You can think about the notebook as an e-book you can execute. You don't really need refactoring tools in an ebook or a slide deck.

**Comment by OliverBarrett** [comment]
Sounds good. Y d'man. Thanks! :)
