### ISSUE TITLE
Add requirements.txt for running on binder

### ISSUE THREAD

**Issue by imagejan** [amueller/introduction_to_ml_with_python#65]
The possibility to run the notebooks from this repository on https://mybinder.org/ would make it even easier to follow those while reading the book.

To make them run on binder, it should be sufficient to add a `requirements.txt` or `environment.yml` file that declares the necessary dependencies.

**Comment by amueller** [comment]
It's on my todo for this week, but pull request also welcome ;)

**Comment by imagejan** [comment]
Done, PR #66 filed. I tested it on my fork with this URL:

https://mybinder.org/v2/gh/imagejan/introduction_to_ml_with_python/binder
