### ISSUE TITLE
Problem on page 71 of showing the animal_tree

### ISSUE THREAD

**Issue by charles-bu** [amueller/introduction_to_ml_with_python#69]
import graphviz
import mglearn

mglearn.plots.plot_animal_tree()

the system did not output the expected decision tree graph but some error message detailed as below,

runfile('D:/Anaconda_Exercise/ML/cp2/cp2_17_decision_tree_model_classification_display.py', wdir='D:/Anaconda_Exercise/ML/cp2')
Traceback (most recent call last):

  File "<ipython-input-2-2a4eae375b92>", line 1, in <module>
    runfile('D:/Anaconda_Exercise/ML/cp2/cp2_17_decision_tree_model_classification_display.py', wdir='D:/Anaconda_Exercise/ML/cp2')

  File "D:\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "D:\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Anaconda_Exercise/ML/cp2/cp2_17_decision_tree_model_classification_display.py", line 19, in <module>
    mglearn.plots.plot_animal_tree()

  File "D:\anaconda3\lib\site-packages\mglearn\plot_animal_tree.py", line 25, in plot_animal_tree
    mygraph.render("tmp")

  File "D:\anaconda3\lib\site-packages\graphviz\files.py", line 146, in render
    rendered = backend.render(self._engine, self._format, filepath)

  File "D:\anaconda3\lib\site-packages\graphviz\backend.py", line 100, in render
    'are on your systems\' path' % args)

RuntimeError: failed to execute ['dot', '-Tpng', '-O', 'tmp'], make sure the Graphviz executables are on your systems' path

￼your advice is highly appreciated!

**Comment by amueller** [comment]
Sorry for the slow reply.

How did you install graphviz? You need to install both ``graphviz-python`` and ``graphviz`` with conda. Using pipy version of graphviz will not work (there is a bunch of issues with installing graphviz).

**Comment by charles-bu** [comment]
thank you so much for your advice, which is highly appreciated.

thank you again for your great book, which brought me into the world of ML. 

by the way, do you have the plan of writing another book of the ML  based on Tensor flow?  

I am very curious about it. if so, just drop a message for us.

Charles

**Comment by amueller** [comment]
I'm not working on another book. There is already several books on tensorflow and deep learning out there.

**Comment by gpvision** [comment]
Hi,
first thank you fo your book, a very good introduction to ML. Very clear and useful to understand different algorithm and associated parameters.

I have the same problem with plot_animal_tree(). I have followed your advices (page 73) : download graphviz 2.38 and install it (msi package). And use conda to finalize. I have updated environment variable (path) to graphviz bin directory. Here versions of different packages 
Python version : 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
Pandas version : 0.20.3
Matplotlib version : 2.0.2
graphviz version : 0.8.4
numpy version : 1.13.1
scipy version : 0.19.1
IPython version : 6.5.0
sklearn version : 0.19.0
mglearn version : 0.1.7
pillow version : 4.2.1

Error returned 
Traceback (most recent call last):

  File "<ipython-input-2-7578903a965f>", line 1, in <module>
    runfile('C:/Users/Philippe_w10_x64/.spyder-py3/test_pg_73.py', wdir='C:/Users/Philippe_w10_x64/.spyder-py3')

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Philippe_w10_x64/.spyder-py3/test_pg_73.py", line 13, in <module>
    mglearn.plots.plot_animal_tree()

  File "C:\Developpement_GPVision\MachineLearningPython\introduction_to_ml_with_python-master\mglearn\mglearn\plot_animal_tree.py", line 25, in plot_animal_tree
    mygraph.render("tmp")

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\graphviz\files.py", line 176, in render
    rendered = backend.render(self._engine, self._format, filepath)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\graphviz\backend.py", line 131, in render
    subprocess.check_call(args, stderr=stderr, **POPEN_KWARGS)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['dot.bat', '-Tpng', '-O', 'tmp']' returned non-zero exit status 1.

Do you have any idea ? Thank you for your help. 
Philippe

**Comment by amueller** [comment]
Hey Philippe. Glad you like the book and sorry you're having issues.
I think the conda package of ``graphviz-python`` can only work with the conda package for ``graphviz``, not the msi package. Do you have both ``graphviz`` and ``graphviz-python`` installed (with conda!) in your environment?

This is unfortunately a bit of a hassle and starting from the next version scikit-learn will have it's own tree plotting routine.

**Comment by gpvision** [comment]
Hi Andreas, thanks for your help. 
Yes, I installed first graphviz msi package and followed by python-graphviz with conda. So I have updated  PATH values for graphviz2.38 directory, anaconda3_64 too and change setup of spyder. Always the same issue.
When I use a cmd window and type dot -V, return is correct.
Error in script only concern the line .render("tmp") !
I did the followig test 
- uninstall graphviz2.38
- keep one path : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Library\bin\graphviz
- start spyder with the script : always error.
Well I continue to read your very good book  and hope to find a solution to try your scripts. It's very useful to understand properly your explanations.

Thank you
Philippe

**Comment by amueller** [comment]
hey Philippe.
As I said, please uninstall the graphviz msi package and install the graphviz conda package.

**Comment by amueller** [comment]
``conda install graphviz python-graphviz``

**Comment by gpvision** [comment]
ok, I never used this command.
Result : 
graphviz : 2.38-hfd603c8_2 installed and also python-graphviz 0.8.4-py36_1
cmd dot -V : return ok. (so PATH ok)
restart computer.
launch spyder and try script with plot_aminal_tree() : always the same issue.
May be it's due to win10 !

**Comment by amueller** [comment]
are you sure spyder is using the same environment that you used to install these packages in?
Not sure if I can help you more, this can be really tricky which is why I'm trying to get rid of this dependency.

**Comment by gpvision** [comment]
I understand, no problem. Anyway thank you for your help. 
And it's really a good idea to get rid of this dependency. It seems like a lot of developer is having a problem with graphviz.
For spyder, I investigate more about your remark.

Thanks again
Philippe
