### ISSUE TITLE
Confused with extended boston dataset features?

### ISSUE THREAD

**Issue by zhugw** [amueller/introduction_to_ml_with_python#70]
From Chapter2: Supervised Learning
> The resulting 104 features are the 13 original features together with the 91 possible combinations of two features within those 13.

But I'm a little confused with this value--91 , I think the number of 13 choose 2 is 78.
```
13! /(2!*(13-2)!) = 78

>>> len(list(itertools.combinations(range(1,14),2)))
78
```

So how did this figure--91--come from?

**Comment by amueller** [comment]
It's with replacement. Not sure which print you have, but the newest says this:

The resulting 104 features are the 13 original features together with the 91 possible
combinations of two features within those 13 (with replacement).

This is 13 interactions for the first feature, plus 12 for the second not involving the first, plus 11 for the third and so on (13 + 12 + 11 + ... + 1 = 91).

**Comment by zhugw** [comment]
Thanks! Got it

```
>>> len(list(itertools.combinations_with_replacement(range(1,14), 2)))
91
```

I used this book :  https://www.amazon.cn/gp/product/B06XGX1KY6/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
