### ISSUE TITLE
Working with text data !tree and !rm

### ISSUE THREAD

**Issue by JujuNollet** [amueller/introduction_to_ml_with_python#74]
# I get an "Invalid syntax" bug on the "!" when I run :

!tree -dL 2 data/aclImdb
!rm -r data/aclImdb/train/unsup

from sklearn.datasets import load_files

reviews_train = load_files("data/aclImdb/train/")

text_train, y_train = reviews_train.data, reviews_train.target
print("type of text_train: {}".format(type(text_train)))
print("length of text_train: {}".format(len(text_train)))
print("text_train[6]:\n{}".format(text_train[6]))

# Help please !

**Comment by amueller** [comment]
You're probably on windows, this will only work on POSIX systems like OS X and Linux. You need to delete the ``data/aclImdb/train/unsup`` folder. I just realized there is no disclaimer about that in the book. I'm sorry for the omission.

**Comment by JujuNollet** [comment]
Thank you for the quick response! Yes I am working with Python 3.6.2 on Windows

How do I do that ? 

Just so you know, I am looking into the "Bag of Words" section of your book and I'm kind of new to programming. I was now trying to code the "Bag-of-Words for Movies Reviews" section and I understand I needed to go back a little to get the information, but im no able to do it because of the "!" situation.

**Comment by amueller** [comment]
Just ignore these two lines. Have you downloaded the data? You need to download and extract it, and then just remove the ``unsup`` folder using the file browser.

**Comment by JujuNollet** [comment]
Is this what you are talking about : 
from sklearn.datasets import load_files

**Comment by amueller** [comment]
No, I'm talking about going to the dataset website and downloading it. Do you have the book?

**Comment by JujuNollet** [comment]
Yes I do but Im not fluent in english and it's my first programming book, I dont really know how to use it since i'm only interested in the bag-of-words section (Im a linguist)

**Comment by amueller** [comment]
Page 325 lists the URL where you can get the dataset. You need to download and unpack it.

**Comment by JujuNollet** [comment]
For me it's actually on the bottom of p.327 but thank you so much I'm doing this right now and I'll ask you more questions if needed!

**Comment by amueller** [comment]
btw, this (free) book might potentially be better suited if you're only interested in text: https://nlp.stanford.edu/IR-book/

**Comment by JujuNollet** [comment]
Hi !! It took me hours to download the data and transfert it on my USB key. 
Here is my code : 

from sklearn.datasets import load_files

reviews_train = load_files("data/aclImdb/train/")

text_train, y_train = reviews_train.data, reviews_train.target
print("type of text_train: {}".format(type(text_train)))
print("length of text_train: {}".format(len(text_train)))
print("text_train[6]:\n{}".format(text_train[6]))

I deleted the file, and delete the two lines that were problematic. But it's still not working :(

Here is the error message : 
Traceback (most recent call last):
  File "D:\Linguistique et Informatique\aclImdb\In[3].py", line 5, in <module>
    reviews_train = load_files("data/aclImdb/train/")
  File "D:\Python\WinPython-32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\sklearn\datasets\base.py", line 201, in load_files
    folders = [f for f in sorted(listdir(container_path))
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'data/aclImdb/train/'

Le chemin d’accès spécifié est introuvable = Cant fin the specified access way

**Comment by amueller** [comment]
Sorry, what exactly took hours?
where did you extract it to?

**Comment by amueller** [comment]
fixed in the next print!
