### ISSUE TITLE
Please help me...

### ISSUE THREAD

**Issue by opuyfb91** [amueller/introduction_to_ml_with_python#77]
I'm a student who are not accustomed to using python.

When I coded 'x, y = make_blobs(n_samples = (400, 50), centers = 2, cluster_std = [7.0, 2.5], random_state = 22)' on the jupyter, The error "unsupported operand type(s) for //: 'tuple' and 'int'" occurred.

What is problem...!

**Comment by amueller** [comment]
Can you please provide a reproducible example?
See https://stackoverflow.com/help/how-to-ask on how to ask questions that make it possible to answer.

**Comment by szaydel** [comment]
@opuyfb91 : `n_samples` should be an int, I believe. It looks like you you are using a tuple `(400, 50)`.

**Comment by amueller** [comment]
In mglearn and newer versions of sklearn (dev version so far only, I think) it can be a tuple. Given that @opuyfb91 posted in this repository, I assume he meant to use the mglearn version, but given that their code is incomplete, it's hard to tell.

**Comment by opuyfb91** [comment]
You are right Dr. amueller. It was all my fault. I should have checked my code.
I used sklearn version... 
Really sorry and Thanks very much for your comment!

**Comment by opuyfb91** [comment]
@amueller 
You are right Dr. amueller. It was all my fault. I should have checked my code.
I used sklearn version...
Really sorry and Thanks very much for your comment!

**Comment by amueller** [comment]
glad you figured it out.
