### ISSUE TITLE
MLPClassifier __init__() got an unexpected keyword argument 'algorithm'

### ISSUE THREAD

**Issue by Amanda-Clark** [amueller/introduction_to_ml_with_python#8]
![ipython](https://cloud.githubusercontent.com/assets/1906954/19834125/f0bc3258-9e0f-11e6-85da-de76f15523f9.png)

I got the above error trying to run the neural network code in chapter 2. I have the latest versions of sklearn and iPython, and am running Python 3.4.3. The notebook code also gives the same result.

**Comment by yinleon** [comment]
Hey @Amanda-Clark I had the same problem. The <a href="http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html">MLPClassifier documentation</a> makes me think that the `algorithm` param should be switched for `solver`. Changing to `solver='lbfgs'` returns a similar result to the textbook.

**Comment by Amanda-Clark** [comment]
This SO post admittedly made me a lot more confused about it.
http://stackoverflow.com/questions/35513237/typeerror-mlpclassifier-got-an-unexpected-keyword-argument-algorithm

**Comment by yinleon** [comment]
Ah yeah, that SO post was from Feb 2016, and the <a href="https://github.com/scikit-learn/scikit-learn/commit/3e12412e053ba5a3e565d5b643f3ded2ef573041#diff-0f0be568a3c3c8f729f42b776d06243b">PR</a> to change `algorithm` to `solver` happened in Sept. The Scikit-Learn package gets updated frequently! Take the good with the bad ;)

**Comment by amueller** [comment]
It needs to be ``"solver"``. Sorry, we overlooked this in the final edits of the book. The change in ``scikit-learn`` was after I wrote the chapter. This will be fixed in the next revision of the book.

**Comment by amueller** [comment]
By the way, if you update the notebooks from this repository, it's already fixed.

**Comment by Amanda-Clark** [comment]
thanks!

**Comment by amueller** [comment]
@Amanda-Clark what's the reason you reopened?

**Comment by Amanda-Clark** [comment]
Accident, never mind.

**Comment by lgaoyangl** [comment]
Just bumped into this issue as I go through the book. Thanks!

**Comment by amueller** [comment]
@lgaoyangl Is that a translation or the English book? As you can see this was fixed quite a while ago so you got an old version of the book, it seems.

**Comment by lgaoyangl** [comment]
@amueller Mine is in English. It was a photocopy version published by Dongnan University Press. I just found out that my book was printed based on the 2016 edition of the original book, so no wonder... quite an old version. Thanks!
