### ISSUE TITLE
avoid confusing mixtire of range and np.arrange on page 77 

### ISSUE THREAD

**Issue by dec1** [amueller/introduction_to_ml_with_python#83]
Hello.
It would be less confusing to use either np.arange or range in the whole snippet  In[63] on p.77, or at least explain clearly why youre using range in one line and np.arange in the next since either would do in both places.
The pull reuest https://github.com/amueller/introduction_to_ml_with_python/pull/82 suggests favouring np.arange since model.feature_importances is also an (nd)array

**Comment by amueller** [comment]
fixed in new print
