### ISSUE TITLE
problems about make_wave in mglearn

### ISSUE THREAD

**Issue by thebigother** [amueller/introduction_to_ml_with_python#84]
Hello,I am a Chinese student who is self-studying ML with your book. In Chapter 2, I tried to copy the code of make_wave on my Geany.Here is what I wrote:
~~~
import matplotlib.pyplot as plt
import mglearn

X,y=mglearn.datasets.make_wave(n_samples=40)
plt.plot=(X,y,'o')
plt.ylim(-3,3)
plt.xlabel('feature')
plt.ylabel('target')

plt.show()
~~~
while nothing came out except two axes and their label names.
I am sure I have installed mglearn properly for I can get exactly the same figure when I tried to copy th code of make_forge.
I am reading the Chinese edition of the book, which is officially published by o'reilly, maybe they made some mistakes in the Chinese edition?

**Comment by amueller** [comment]
there's a ``=`` after plt.plot that doesn't belong there.

**Comment by amueller** [comment]
Sorry for the slow reply.

**Comment by kentx** [comment]
骚男，plt.plot=()  多了个等于，应该是 点
