### ISSUE TITLE
redundant pca.transform() following pca.fit_transform()

### ISSUE THREAD

**Issue by dec1** [amueller/introduction_to_ml_with_python#86]
Hello,

Below the comment "# extract eigenfaces from lfw data and transform data":

```
pca.fit_transform(X_people)
X_pca = pca.transform(X_people)
```
The double `transform `is redundant and confusing since many readers may presume there's some purpose they don't understand.
I'd suggest removing the second transform (as in [pull request](https://github.com/amueller/introduction_to_ml_with_python/pull/82)] or alternatively changing the `fit_transform ` to just `fit`

**Comment by amueller** [comment]
thanks!

**Comment by amueller** [comment]
fixed in new print, I'll update this repo tomorrow.
