### ISSUE TITLE
"rescales to same scale" page 152

### ISSUE THREAD

**Issue by dec1** [amueller/introduction_to_ml_with_python#87]
> "PCA, which rescales the principal components to have the same scale"

This somewhat tautological phrase is unclear, would benefit from rewording  
eg 

> .. so that the data as a function of each of the principal components has similar variance

**Comment by amueller** [comment]
@dec1 the errata page at oreilly is back up again. Would you mind filing the errata again there?

**Comment by amueller** [comment]
fixed in next print
