### ISSUE TITLE
Issue with mg_learn.datasets.make_forge

### ISSUE THREAD

**Issue by jeweltiwari** [amueller/introduction_to_ml_with_python#93]
Hello,

I just started with your book and facing the following issue.
AttributeError                            Traceback (most recent call last)
<ipython-input-29-a6d31fa79116> in <module>()
      1 from sklearn.model_selection import train_test_split
----> 2 X,y = mglearn.datasets.make_forge()

AttributeError: module 'mglearn' has no attribute 'datasets'

Please advise.

**Comment by amueller** [comment]
Hey. How did you install mglearn?

**Comment by jeweltiwari** [comment]
pip install mglearn through the anaconda command prompt

**Comment by amueller** [comment]
Sorry for the slow reply. Is there by any chance a file in the folder called mglearn?
Can you do ``mglearn.__path__``?

**Comment by jacmus** [comment]
I am facing the same problem. 

It seems that the package sklearn is missing.

Please, check and advise.

Thank you.

**Comment by jeweltiwari** [comment]
Hi Andreas, I tried it on Spyder instead of Jupyter notebooks and it worked.

**Comment by jacmus** [comment]
Hi,

I added the following line before calling "mglearn.datasets.make_forge()"  and it worked:

Import sklearn

Thank you.

**Comment by amueller** [comment]
@jacmus that change is probably unrelated to it working now. More likely restarting the IDE or something similar solved the issue.
