### ISSUE TITLE
  How can i resolve this errror NameError: name 'mglearn' is not defined

### ISSUE THREAD

**Issue by fareedsyed** [amueller/introduction_to_ml_with_python#95]
I have installed mglearn through pip command when i run the following
 # create a scatter matrix from the dataframe, color by y_train
pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15),
                           marker='o', hist_kwds={'bins': 20}, s=60,
                           alpha=.8, cmap=mglearn.cm3)

command i am getting an error:

pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15),       6                            marker='o', hist_kwds={'bins': 20}, s=60, ----> 7                            alpha=.8, cmap=mglearn.cm3)

**Comment by amueller** [comment]
``import mglearn``.

**Comment by PurushothamanSrikanth** [comment]
@fareedsyed You need to import `mglearn` package inside your code. You can do that using `import mglearn`

For more details on `mglearn` package visit: [](https://pypi.org/project/mglearn/)

**Comment by shubham-011** [comment]
For future visitors, since mglearn is jupyter specific, you have to install it in anaconda prompt using `pip install mglearn`and after that only `import mglearn` will work in jupyter notebook.

**Comment by powerskyroom100** [comment]
Memory.__init__() got an unexpected keyword argument 'cachedir'

**Comment by amueller** [comment]
@shubham-011 it is not jupyter specific, it's a pip-installable package, that you need to install in the same environment that your jupyter kernel runs in.

**Comment by amueller** [comment]
Also, instructions are on the frontpage of this repo: https://github.com/amueller/introduction_to_ml_with_python#introduction-to-machine-learning-with-python
