### ISSUE TITLE
Undefined Name: Where is make_dataset() defined?

### ISSUE THREAD

**Issue by cclauss** [amueller/introduction_to_ml_with_python#96]
https://github.com/amueller/introduction_to_ml_with_python/search?q=make_dataset&unscoped_q=make_dataset

[flake8](http://flake8.pycqa.org) testing of https://github.com/amueller/introduction_to_ml_with_python on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./mglearn/plot_kneighbors_regularization.py:11:16: F821 undefined name 'make_dataset'
        x, y = make_dataset(n_samples)
               ^
1     F821 undefined name 'make_dataset'
1
```

**Comment by amueller** [comment]
Looks like ``plot_regression_datasets`` is unused and can be removed.
Is there a reason you're concerned with flake8 errors in mglearn?

**Comment by cclauss** [comment]
This repo was on https://github.com/trending/jupyter-notebook and I merely wanted to see how many of the  trending notebooks were Python 3 ready.

**Comment by amueller** [comment]
Ah. It's Python3 "ready". It's gonna be Python3 only pretty soon, probably.

**Comment by cclauss** [comment]
Yes.  This repo is Py3 ready but it was disappointing to see how many other repos on the trending list were not.

**Comment by amueller** [comment]
The trending list seems to show many non-jupyter repos despite the jupyter filter... weird. Anyway I removed this function from the (secret) main repo an it'll go with the next sync, probably next week after the new version of the book comes out.

**Comment by cclauss** [comment]
Are you interested to add automated testing? Travis CI, Circle CI, AppVeyor to the repo?

**Comment by amueller** [comment]
yes, very. Parts may be too long to run, though. I'm also actually thinking about splitting up the notebooks more because they take too long to load in jupyter and/or crash the browser :-/

**Comment by cclauss** [comment]
Which on Travis, Circle, or AppVeyor?

**Comment by amueller** [comment]
travis or circle. Travis gives more runs but I think has shorter timeouts.

**Comment by amueller** [comment]
you could check how long 3 or 7 are running. my guess would be that they take too long for CI. There could be some shortcuts using mocking maybe?

**Comment by cclauss** [comment]
Fixed: https://github.com/amueller/introduction_to_ml_with_python/search?q=make_dataset&unscoped_q=make_dataset
