### ISSUE TITLE
mglearn folder

### ISSUE THREAD

**Issue by jamessv** [amueller/introduction_to_ml_with_python#98]
> copy the mglearn folder and preamble.py into the folder where you're running your jupyter notebooks (I have my own separate folder for the jupyter notebooks that I make when following this book)

From here https://github.com/amueller/introduction_to_ml_with_python/
I need to copy mglearn folder and preamble.py file to where ?
My Anaconda installed location is:
C:\ProgramFiles\Anaconda2.5.0.0.64\Scripts\jupyter.exe
C:\ProgramFiles\Anaconda2.5.0.0.64\Lib\site-packages\jupyterlab
C:\Users\abc\.jupyter

**Comment by amueller** [comment]
The best way is really to run ``pip install mglearn``. If this doesn't work, check out https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by jamessv** [comment]
mglearn already installed, actually I am trying to install preamble also on Windows 64

**Comment by christian512** [comment]
Hi @jamessv ,
you need to copy the `mglearn`-folder and the `preamble.py` into the folder, where your Jupyter notebook is saved. 
If in your case the notebook is located at `C:\Users\abc.ipynb` then you need to copy `mglearn` and `preamble.py` to `C:\Users\`.
Hope this helps.

**Comment by jamessv** [comment]
> Hi @jamessv ,
> you need to copy the `mglearn`-folder and the `preamble.py` into the folder, where your Jupyter notebook is saved.
> If in your case the notebook is located at `C:\Users\abc.ipynb` then you need to copy `mglearn` and `preamble.py` to `C:\Users\`.
> Hope this helps.

Where my notebook located ?
C:\Users\abc\.jupyter ?

**Comment by christian512** [comment]
To see where your notebook is located run

```
import os
print(os.getcwd())
```

To see what is in that directory use
`print(os.getlist())`

The list should include `mglearn` and `preamble.py`. If not, you need to copy these to the directory you got from `print(os.getcwd())`.

**Comment by jamessv** [comment]
Solved

**Comment by amueller** [comment]
you can also just ``pip install mglearn`` btw.

**Comment by Tan-Juan-hub** [comment]
@jamessv 
How did you solve it?
Thanks.

**Comment by amueller** [comment]
@Tan-Juan-hub please see my answer above. Did you run ``pip install mglearn``? If so and you're still having an issue, please open a new issue.
