### ISSUE TITLE
Undefined name: 'from IPython import get_ipython' before '%matplotlib inline'

### ISSUE THREAD

**Issue by cclauss** [amueller/introduction_to_ml_with_python#99]
In notebooks 2, 3, 4, and 7, flake8 complains:
```
stdin:7:1: F821 undefined name 'get_ipython'
get_ipython().run_line_magic('matplotlib', 'inline')
^
```
To supress these issues, the line __from IPython import get_ipython__ should be added before the line __%matplotlib inline__.  _Explicit is better than implicit_.

**Comment by amueller** [comment]
I don't think that's right. It's a notebook file. It could be added in the conversion.

**Comment by cclauss** [comment]
It is related to some magic that IPython does... ipython/traitlets/issues#502

**Comment by cclauss** [comment]
The issue is that __%matplotlib inline__ gets expanded to __get_ipython().magic(u'matplotlib inline')__ but flake8 wants to see __from IPython import get_ipython__ before it sees a call to __get_ipython()__.

**Comment by amueller** [comment]
But that's an issue of the converter, not the notebook. In the notebook it's pretty explicit that this is an ipython magic because it's in a notebook.

**Comment by amueller** [comment]
@lovebuggg this is unrelated to the issue discussed here. Also, it's not a problem, it's a warning. You can use the notebooks in this repository and you won't get a warning (using make_blobs directly from scikit-learn as the warning says).
